(function(g){var window=this;'use strict';var uV=function(e){e.publish("cardstatechange",e.Vk()&&e.Y1()?1:0)},mj=function(e,K){var S=g.eY(K),I=S?K:arguments;
for(S=S?0:1;S<I.length;S++){if(e==null)return;e=e[I[S]]}return e},aJD=function(e){var K=g.OR(e);
e=g.Ry(e);return new g.Gh(K.x,K.y,e.width,e.height)},Hmk=function(e,K,S){var I=I===void 0?{}:I;
var A;return A=g.lX(e,K,function(){g.tf(A);S.apply(e,arguments)},I)},qV=function(e){e=g.Ia(e);
delete LC[e];g.WS(LC)&&Jq&&Jq.stop()},QhD=function(){Jq||(Jq=new g.Wg(function(){c1a()},20));
var e=Jq;e.isActive()||e.start()},c1a=function(){var e=g.PS();
g.Q4(LC,function(K){Zm6(K,e)});
g.WS(LC)||QhD()},Ed=function(e,K,S,I){g.VB.call(this);
if(!Array.isArray(e)||!Array.isArray(K))throw Error("Start and end parameters must be arrays");if(e.length!=K.length)throw Error("Start and end points must be the same length");this.L=e;this.N=K;this.duration=S;this.G=I;this.coords=[];this.progress=this.Z=0;this.W=null},Zm6=function(e,K){K<e.startTime&&(e.endTime=K+e.endTime-e.startTime,e.startTime=K);
e.progress=(K-e.startTime)/(e.endTime-e.startTime);e.progress>1&&(e.progress=1);e.Z=1E3/(K-e.W);e.W=K;r1e(e,e.progress);e.progress==1?(e.S=0,qV(e),e.onFinish(),e.cg()):e.isPlaying()&&e.Cd()},r1e=function(e,K){typeof e.G==="function"&&(K=e.G(K));
e.coords=Array(e.L.length);for(var S=0;S<e.L.length;S++)e.coords[S]=(e.N[S]-e.L[S])*K+e.L[S]},CAa=function(e,K){g.FG.call(this,e);
this.coords=K.coords;this.x=K.coords[0];this.y=K.coords[1];this.z=K.coords[2];this.duration=K.duration;this.progress=K.progress;this.fps=K.Z;this.state=K.S},lV=function(e,K,S,I,A){Ed.call(this,K,S,I,A);
this.element=e},OmK=function(e,K,S,I,A){if(K.length!=2||S.length!=2)throw Error("Start and end points must be 2D");
lV.call(this,e,K,S,I,A)},shS=function(e){return Math.pow(e,3)},DWa=function(e){return 3*e*e-2*e*e*e},Rlu=function(e){g.B.call(this);
this.L=e||window;this.S=[]},tq=function(e){return e.baseUrl||null},v$=function(e,K){return g.GC(g.Co(e,K),function(S){return!!S})},dWn=function(e,K,S){function I(IY){var F=IY.hovercardButton;
if(!F)return null;F=F.subscribeButtonRenderer;if(!F)return null;var Ve=k(F.unsubscribedButtonText),z=k(F.subscribedButtonText);if(F.subscribed){var Tu=k(F.subscriberCountWithUnsubscribeText);var E8=k(F.subscriberCountText)}else Tu=k(F.subscriberCountText),E8=k(F.subscriberCountWithSubscribeText);var CO=null;if(IY.signinEndpoint){CO=mj(IY,"signinEndpoint","webNavigationEndpointData","url");if(!CO){var Ju,hu;CO=(hu=g.Q((Ju=F.signInEndpoint)==null?void 0:Ju.commandMetadata,g.Vg))==null?void 0:hu.url}if(!CO)return null}return Ve&&
(z||CO)?{subscribed:F.subscribed,subscribeText:Ve,subscribeCount:Tu,unsubscribeText:z,unsubscribeCount:E8,enabled:F.enabled,signinUrl:CO,classic:IY.useClassicSubscribeButton}:null}
function A(IY){if(IY){var F=[],Ve=IY.videoId;Ve&&F.push("v="+Ve);(Ve=IY.playlistId)&&F.push("list="+Ve);(IY=IY.startTimeSeconds)&&F.push("t="+IY);return"/watch?"+F.join("&")}}
function k(IY){if(!IY)return null;var F=IY.simpleText;return F?F:IY.runs?g.Co(IY.runs,function(Ve){return Ve.text}).join(""):null}
K=K.endscreenElementRenderer;if(!K)return null;var P=K.style,b=K.endpoint||{},N=null,h=null,n=!1,V=null,w=null,T=null,Y=null,u=!1,L=null,q=null,E=null,t=null,U=null,H=null;if(P==="VIDEO")g.Q(b,g.Z3)?N=g.Q(b,g.Z3).url:(H=g.Q(b,g.Ar),N=A(H)),h=!1,V=e,K.thumbnailOverlays?(n=K.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,w=k(n.text),n=n.style==="LIVE"):w=k(K.videoDuration);else if(P==="PLAYLIST")g.Q(b,g.Z3)?N=g.Q(b,g.Z3).url:(H=g.Q(b,g.Ar),N=A(H)),h=!1,V=e,T=k(K.playlistLength);else if(P===
"CHANNEL"){if(u=mj(b,"browseEndpoint","browseId"))Y=u,N="/channel/"+Y;h=!1;V="new";(u=!!K.isSubscribe)?L=I(K):q=k(K.subscribersText)}else P==="WEBSITE"?((E=mj(b,"urlEndpoint","url"))&&(N=E),h=!0,V="new",E=K.icon.thumbnails[0].url):P==="CREATOR_MERCHANDISE"&&(K.productPrice&&(t=k(K.productPrice)),K.additionalFeesText&&(U=k(K.additionalFeesText)),(h=mj(b,"urlEndpoint","url"))&&(N=h),h=!0,V="new");e=mj(K,"title","accessibility","accessibilityData","label");var R=K.endpoint?K.endpoint.clickTrackingParams:
null,O="";if(K.metadata){var SO=k(K.metadata);SO&&(O=SO)}return{id:"element-"+S,type:P,title:k(K.title),metadata:O,callToAction:k(K.callToAction),vU:K.image,iconUrl:E,left:Number(K.left),width:Number(K.width),top:Number(K.top),aspectRatio:Number(K.aspectRatio),startMs:Math.floor(Number(K.startMs)),endMs:Math.floor(Number(K.endMs)),videoDuration:w,QY:n,playlistLength:T,channelId:Y,subscribeButton:L,subscribersText:q,isSubscribe:u,targetUrl:N||null,dPt:h,sessionData:R?{itct:R}:null,JrV:V,Rv:e?e:null,
isPlaceholder:K.isPlaceholder,impressionUrls:v$(K.impressionUrls||[],tq),irG:v$(K.hovercardShowUrls||[],tq),clickUrls:v$(b.loggingUrls||[],tq),visualElement:g.l8(K.trackingParams),productPrice:t,additionalFeesText:U,watchEndpoint:H||null}},zle=function(e,K){var S={startMs:Math.floor(Number(e.startMs)),
impressionUrls:v$(e.impressionUrls||[],tq),elements:v$(e.elements||[],function(I,A){return dWn(K,I,A)})};
e.trackingParams&&(S.visualElement=g.l8(e.trackingParams));return S},FAD=function(e){g.NK.call(this,e);
this.W=this.endscreen=null;this.L={};this.Z={};this.G=this.Y=null;this.j=[];this.S=null;this.zA=!0;this.N=0;e=e.J();this.U=g.cM(e)||g.ZA(e);this.events=new g.Qv(this);g.c(this,this.events);this.events.T(this.player,g.Mc("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.bk("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.dN);this.events.T(window,"focus",this.O3_);this.load();var K=g.W3("STYLE");(g.rK("HEAD")[0]||document.body).appendChild(K);this.addOnDisposeCallback(function(){g.AC(K)});
K.sheet&&(K.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),K.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},WAa=function(e){return e.player.getVideoData().Xo?"current":e.U?"new":"current"},jP=function(e){return e.player.J().playerStyle==="creator-endscreen-editor"},etK=function(e){var K=e.player.getVideoData(),S=K.videoId;
e.W&&e.W.abort();S={method:"POST",onFinish:function(A){var k=e.W=null;A.status===200&&(A=A.responseText,A.substring(0,3)===")]}"&&(A=A.substring(3),k=JSON.parse(A),k=zle(k,WAa(e))));pC(e,k)},
urlParams:{v:S},withCredentials:!0};e.U&&(S.urlParams.ptype="embedded");var I=K.Z_;I&&(S.postParams={ad_tracking:I});if(K=g.hSN(K))if(K=g.Ru(K),K=g.CG(K))e.W=g.vO(K,S)},pC=function(e,K,S){S=S===void 0?!0:S;
e.player.TE("creatorendscreen");e.Y&&(e.Y.dispose(),e.Y=null,e.G.dispose(),e.G=null);for(var I=g.f(Object.values(e.L)),A=I.next();!A.done;A=I.next())A.value.dispose();e.L={};e.Z={};e.j.length>0&&(e.j.forEach(function(b){b.dispose()}),e.j.length=0);
e.S&&(g.b1(e.S,"ytp-ce-element-show"),e.S.setAttribute("aria-hidden","true"));e.N=0;if((e.endscreen=K)&&K.elements){S&&K3Y(e);S=[];I=new g.gi(K.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});S.push(I);e.player.J().L||(e.Y=new g.C({K:"div",C:"ytp-ce-shadow"}),g.QA(e.player,e.Y.element,4),e.G=new g.P8(e.Y,200));for(I=0;I<K.elements.length;++I){A=K.elements[I];var k=Sqn(e,A);if(k){e.L[A.id]=k;e.Z[A.id]=A;g.QA(e.player,k.element,4);var P=new g.gi(A.startMs,A.endMs,{id:"ytp-ce-element-"+
A.id,namespace:"creatorendscreen"});S.push(P);IfY(e,k,A)}else g.cl(new g.W6("buildEndscreenElement null",A))}e.player.va(S);e.dN()}},K3Y=function(e){var K=g.vl(),S=g.jB();
S&&K&&e.endscreen.visualElement&&g.I5(g.Wl)(void 0,S,K,e.endscreen.visualElement)},Sqn=function(e,K){var S=null;
switch(K.type){case "VIDEO":e={K:"div",kA:["ytp-ce-element","ytp-ce-video"],B:{tabindex:"0","aria-label":K.Rv||"","aria-hidden":"true"},X:[{K:"div",C:"ytp-ce-element-shadow"},{K:"div",C:"ytp-ce-covering-image",B:xO(K)},{K:"div",C:"ytp-ce-covering-shadow-top"},{K:"a",C:"ytp-ce-covering-overlay",B:{href:GV(e,K.targetUrl),tabindex:"-1"},X:[{K:"div",kA:["ytp-ce-video-title","ytp-webkit-ellipsis"],B:{dir:g.fp(K.title||"")},YA:K.title},{K:"div",C:K.QY?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
YA:K.videoDuration||void 0}]}]};S=new g.C(e);break;case "PLAYLIST":e={K:"div",kA:["ytp-ce-element","ytp-ce-playlist"],B:{tabindex:"0","aria-label":K.Rv||"","aria-hidden":"true"},X:[{K:"div",C:"ytp-ce-element-shadow"},{K:"div",C:"ytp-ce-covering-image",B:xO(K)},{K:"div",C:"ytp-ce-covering-shadow-top"},{K:"a",C:"ytp-ce-covering-overlay",B:{href:GV(e,K.targetUrl),tabindex:"-1"},X:[{K:"div",kA:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],B:{dir:g.fp(K.title||"")},YA:K.title},{K:"div",C:"ytp-ce-playlist-count",
X:[{K:"div",C:"ytp-ce-playlist-icon"},{K:"div",C:"ytp-ce-playlist-count-text",YA:K.playlistLength||void 0}]}]}]};S=new g.C(e);break;case "CHANNEL":S={K:"div",kA:["ytp-ce-element","ytp-ce-channel",K.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],B:{tabindex:"0","aria-label":K.Rv||"","aria-hidden":"true"},X:[{K:"div",C:"ytp-ce-element-shadow"},{K:"div",C:"ytp-ce-expanding-overlay",X:[{K:"div",C:"ytp-ce-expanding-overlay-hider"},{K:"div",C:"ytp-ce-expanding-overlay-background"},{K:"div",C:"ytp-ce-expanding-overlay-content",
X:[{K:"div",C:"ytp-ce-expanding-overlay-body",X:[{K:"div",C:"ytp-ce-expanding-overlay-body-padding",X:[{K:"a",kA:["ytp-ce-channel-title","ytp-ce-link"],B:{href:GV(e,K.targetUrl),target:"_blank",tabindex:"-1",dir:g.fp(K.title||"")},YA:K.title},K.subscribeButton?{K:"div",C:"ytp-ce-subscribe-container",X:[{K:"div",C:"ytp-ce-channel-subscribe"}]}:"",K.subscribersText?{K:"div",C:"ytp-ce-channel-subscribers-text",YA:K.subscribersText}:"",K.metadata?{K:"div",kA:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],YA:K.metadata}:""]}]}]}]},{K:"div",C:"ytp-ce-expanding-image",B:xO(K)}]};S=new g.C(S);var I=g.OH(document,"div","ytp-ce-channel-subscribe",S.element)[0];if(K.subscribeButton&&K.channelId){g.o3(I,"ytp-ce-subscribe-button");if(e.player.J().L){var A=null;var k=K.sessionData.itct}else A="endscreen",k=null;A=new g.OZ(K.subscribeButton.subscribeText,K.subscribeButton.subscribeCount,K.subscribeButton.unsubscribeText,K.subscribeButton.unsubscribeCount,!!K.subscribeButton.enabled,!!K.subscribeButton.classic,
K.channelId,!!K.subscribeButton.subscribed,A,k,e.player,!1);I.appendChild(A.element);e.j.push(A)}break;case "WEBSITE":e={K:"div",kA:["ytp-ce-element","ytp-ce-website"],B:{tabindex:"0","aria-label":K.Rv||"","aria-hidden":"true"},X:[{K:"div",C:"ytp-ce-element-shadow"},{K:"div",C:"ytp-ce-expanding-overlay",X:[{K:"div",C:"ytp-ce-expanding-overlay-hider"},{K:"div",C:"ytp-ce-expanding-overlay-background"},{K:"div",C:"ytp-ce-expanding-overlay-content",X:[{K:"div",C:"ytp-ce-expanding-overlay-body",X:[{K:"div",
C:"ytp-ce-expanding-overlay-body-padding",X:[{K:"div",C:"ytp-ce-website-title",B:{dir:g.fp(K.title||"")},YA:K.title},{K:"div",C:"ytp-ce-website-metadata",YA:K.metadata},{K:"a",kA:["ytp-ce-website-goto","ytp-ce-link"],B:{href:GV(e,K.targetUrl),target:"_blank",tabindex:"-1"},YA:K.callToAction}]}]}]}]},{K:"div",C:"ytp-ce-expanding-image",B:xO(K)},{K:"div",C:"ytp-ce-expanding-icon",B:AlS(K.iconUrl)}]};S=new g.C(e);break;case "CREATOR_MERCHANDISE":S="",K.productPrice&&(S={K:"div",C:"ytp-ce-merchandise-price-container",
X:[{K:"div",C:"ytp-ce-merchandise-price",YA:K.productPrice}]},K.additionalFeesText&&S.X.push({K:"div",C:"ytp-ce-merchandise-additional-fees",YA:K.additionalFeesText})),e={K:"div",kA:["ytp-ce-element","ytp-ce-merchandise"],B:{tabindex:"0","aria-label":K.Rv||"","aria-hidden":"true"},X:[{K:"div",C:"ytp-ce-element-shadow"},{K:"div",C:"ytp-ce-expanding-overlay",X:[{K:"div",C:"ytp-ce-expanding-overlay-hider"},{K:"div",C:"ytp-ce-expanding-overlay-background"},{K:"div",C:"ytp-ce-expanding-overlay-content",
X:[{K:"div",C:"ytp-ce-expanding-overlay-body",X:[{K:"div",C:"ytp-ce-expanding-overlay-body-padding",X:[{K:"div",C:"ytp-ce-merchandise-title",B:{dir:g.fp(K.title||"")},YA:K.title},S,{K:"div",C:"ytp-ce-merchandise-metadata",YA:K.metadata},{K:"a",kA:["ytp-ce-merchandise-goto","ytp-ce-link"],B:{href:GV(e,K.targetUrl),target:"_blank",tabindex:"-1"},YA:K.callToAction}]}]}]}]},{K:"div",C:"ytp-ce-expanding-image",B:xO(K)},{K:"div",C:"ytp-ce-merchandise-invideo-cta-container",X:[{K:"div",C:"ytp-ce-merchandise-invideo-cta",
YA:K.callToAction||void 0}]}]},S=new g.C(e)}K.isPlaceholder&&g.o3(S.element,"ytp-ce-placeholder");return S},xO=function(e){if(e.vU)var K=e.vU.thumbnails;
return AlS(K?K[K.length-1].url:null)},AlS=function(e){return e?{style:"background-image: url("+e+")"}:{}},IfY=function(e,K,S){function I(N){N&&(K.listen("blur",function(){N.style.display!="none"&&e.zA&&N.focus()}),K.T(N,"focus",k),K.T(N,"blur",P))}
function A(N){e.N+=N;e.N>0?(g.o3(K.element,"ytp-ce-force-expand"),Ud(e,S.id,!0)):(g.b1(K.element,"ytp-ce-force-expand"),g.b1(K.element,"ytp-ce-element-hover"),Ud(e,S.id,!1))}
function k(){A(1)}
function P(){A(-1)}
K.listen("mouseenter",function(){km4(e,K,S)});
K.listen("mouseleave",function(){i8Y(e,K,S)});
e.player.J().L||K.listen("click",function(){g.o3(K.element,"ytp-ce-element-hover")});
K.listen("click",function(N){P_u(e,S,N)});
K.listen("keypress",function(N){P_u(e,S,N)});
K.listen("focus",function(){km4(e,K,S)});
K.listen("blur",function(){i8Y(e,K,S)});
K.listen("touchstart",function(){km4(e,K,S)});
var b=g.sH("ytp-ce-expanding-overlay-hider",K.element);b&&K.T(b,"touchstart",function(N){N.stopPropagation();g.b1(K.element,"ytp-ce-element-hover");g.b1(K.element,"ytp-ce-force-expand")});
K.listen("keydown",function(N){e.zA=N.keyCode===9&&!N.shiftKey});
I(g.sH("ytp-sb-subscribe",K.element));I(g.sH("ytp-sb-unsubscribe",K.element));K.listen("focus",k);K.listen("blur",P)},P_u=function(e,K,S){if(K.targetUrl&&(!S||S.type!=="keypress"||S.keyCode===13)){for(var I=S.target;I&&!g.g1(I,"ytp-ce-element");){g.g1(I,"subscribe-label")&&gV6(e,K);
if(g.g1(I,"ytp-ce-channel-subscribe"))return;I=I.parentElement||null}if(!I||g.g1(I,"ytp-ce-element-hover")){S.preventDefault();S.stopPropagation();if(I=e.L[K.id])i8Y(e,I,K),I.element.blur();if(S.ctrlKey||S.metaKey||K.JrV==="new")gV6(e,K),e.player.sendVideoStatsEngageEvent(17,void 0),e.player.pauseVideo(),S=g.Ru(GV(e,K.targetUrl)),S=g.CG(S),g.Rj(S,void 0,K.sessionData);else{var A=g.SW(e.player.J())||e.player.getVideoData().Xo,k=function(){var P=GV(e,K.targetUrl),b=K.sessionData,N=K.watchEndpoint,h=
g.o5(P);A&&h&&(h.v||h.list)?e.player.Ze(h.v,b,h.list,!1,void 0,N||void 0):g.DQ(P,b)};
gV6(e,K,function(){e.player.sendVideoStatsEngageEvent(17,k)})}}}},GV=function(e,K){e=e.player.J();
if(K){if(K.startsWith("//"))return e.protocol+":"+K;if(K.startsWith("/"))return g.oU(e)+K}else return"";return K},km4=function(e,K,S){g.g1(K.element,"ytp-ce-element-hover")||(S.type==="VIDEO"||S.type==="PLAYLIST"?g.o3(K.element,"ytp-ce-element-hover"):e.player.J().L?(new g.Wg(function(){g.o3(K.element,"ytp-ce-element-hover")},200)).start():g.o3(K.element,"ytp-ce-element-hover"),yc(e,S.irG),Ud(e,S.id,!0))},i8Y=function(e,K,S){g.b1(K.element,"ytp-ce-element-hover");
g.b1(K.element,"ytp-ce-force-expand");Ud(e,S.id,!1)},Ud=function(e,K,S){e.Y&&(S?e.G.show():e.G.hide());
for(var I=g.f(Object.keys(e.L)),A=I.next();!A.done;A=I.next())A=A.value,A!==K&&g.np(e.L[A].element,"ytp-ce-element-shadow-show",S)},yc=function(e,K,S){function I(){k||(A++,A===K.length&&(P.stop(),S&&S()))}
if(!K||K.length===0||jP(e))S&&S();else{K=oVK(e,K);var A=0,k=!1,P=new g.Wg(function(){k=!0;S&&S()},1E3,e);
P.start();for(e=0;e<K.length;e++)g.OS(K[e],I)}},gV6=function(e,K,S){yc(e,K.clickUrls,S);
(e=g.jB())&&K.dPt&&g.bB(e,K.visualElement)},oVK=function(e,K){var S=e.player.getVideoData().clientPlaybackNonce;
e=e.player.getCurrentTime().toFixed(2);S={CPN:S,AD_CPN:S,MT:e};e=[];for(var I=0;I<K.length;I++)e.push(MK4(K[I],S));return e},MK4=function(e,K){return e.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(S){var I=unescape(S);
I=I.substring(1,I.length-1);return K[I]?escape(K[I]):S})},b8a=function(e){return typeof e==="string"?e:""},B$=function(e,K,S){for(var I in K)if(K[I]===e)return e;
return S},Ndk=function(e,K,S,I){this.value=e;
this.target=K;this.showLinkIcon=S;this.S=I},a0=function(e){return e.value?e.value:null},H$=function(e){if(!e)return null;
var K=g.Ru(b8a(e.value));K=g.CG(K);if(!K)return null;var S=B$(e.target,htu,"current");if(S==null)e=null;else{var I=e.show_link_icon;e=new Ndk(K,S,I==="true"||I==="false"?I==="true":!0,e.pause_on_navigation!=null?e.pause_on_navigation:!0)}return e},nVe=function(e,K,S){this.type=e;
this.trigger=K;this.url=S},Td4=function(e){if(!e)return null;
var K=B$(e.type,VKe),S=B$(e.trigger,wv6);e=e.url;e=Array.isArray(e)&&e.length?e[0]:e;e=H$(e?e:null);return K?new nVe(K,S,e):null},Yq4=function(e,K,S,I,A){this.id=e;
this.type=K;this.style=S;this.data=A;this.action=I||[]},Xvn=function(e,K){return g.we(e.action,K)},ffY=function(e,K){this.context=e;
this.S=K},$pu=function(e){return e.customMessage?c$("div","iv-card-message",e.customMessage):""},Qc=function(e,K){e="background-image: url("+e+");";
var S=[];K&&S.push(K);return{K:"div",C:"iv-card-image",B:{style:e},X:S}},uAi=function(e){if(!e.metaInfo||e.metaInfo.length===0)return"";
var K=[];e=g.f(e.metaInfo);for(var S=e.next();!S.done;S=e.next())K.push(c$("li","",S.value));return{K:"ul",C:"iv-card-meta-info",X:K}},c$=function(e,K,S){K?typeof K==="string"?K={"class":K}:Array.isArray(K)&&(K={"class":K.join(" ")}):K={};
K.dir=g.fp(S);return{K:e,B:K,YA:S}},mp4=function(e){if(!e.customMessage)return"";
var K=["iv-card-action","iv-card-primary-link"],S={};e.FU&&(K.push("iv-card-action-icon"),S.style="background-image: url("+e.FU+");");S.dir=g.fp(e.customMessage);var I=[{K:"span",YA:e.customMessage}];e.showLinkIcon&&(I.push("\u00a0"),I.push({K:"span",C:"iv-card-link-icon"}));return{K:"div",kA:K,B:S,X:I}},ZP=function(e,K,S,I){if(I){K=g.f(K);
for(var A=K.next();!A.done;A=K.next())e.S(A.value,I,S.id,S.sessionData,S.lB.click,5)}},L3u=function(e,K){this.merchant=e;
this.price=K},Jla=function(e){var K;
(K=e)&&!(K=e.length>1?e.charAt(0)==="/"&&e.charAt(1)!=="/":e==="/")&&(K=e.replace(/^(https?:)?\/\//,"").split("/",1),K=!K||K.length<1||!K[0]?[]:K[0].toLowerCase().split(".").reverse(),K=K[0]==="com"&&K[1]==="youtube"||K[0]==="be"&&K[1]==="youtu");return K?e.indexOf("/redirect?")===-1:!1},qqS=function(e,K){return K?K:Jla(e)?"current":"new"},rl=function(e,K){g.B.call(this);
var S=this;this.element=e;this.context=K;this.p8=!1;this.cY=new Map;this.Js=new Map;this.context.V.addEventListener(g.Mc("annotations_module"),function(I){(I=S.cY.get(I))&&I.apply(S)});
this.context.V.addEventListener(g.bk("annotations_module"),function(I){(I=S.Js.get(I))&&I.apply(S)})},CC=function(e,K,S,I,A,k,P){e.context.S.listen(K,"click",function(b){e.hT(S,I,A,k||[],P||0,b)});
e.context.S.listen(K,"touchstart",function(){e.p8=!1});
e.context.S.listen(K,"touchmove",function(){e.p8=!0})},EVa=function(e){var K;
return((K=g.Q(e,g.Z3))==null?0:K.url)?g.Q(e,g.Z3).url:(e=g.Q(e,g.Ar))&&e.videoId?(K="/watch?v="+e.videoId,e.playlistId&&(K+="&list="+e.playlistId),e.index&&(K+="&index="+e.index),e.startTimeSeconds&&(K+="&t="+e.startTimeSeconds),K):null},Od=function(e,K,S){return{CK:(e.impressionLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""}),
click:(S.loggingUrls||[]).map(function(I){return I.baseUrl||""}),
close:(K.dismissLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""}),
oT:(K.impressionLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""}),
md:(K.clickLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""})}},lfK=function(e,K,S){rl.call(this,K,S);
var I=this;this.V=e;this.eventId=null;this.L8=this.eG=this.b6=this.Y=this.isInitialized=!1;this.cards=[];this.PN=this.j=this.RS=this.G=this.Cr=this.S=null;this.zA=[];this.rY=this.N=this.Lv=this.QA=null;this.Z=0;this.VA=new g.Wg(function(){},S.PY.M4?4E3:3E3);
g.c(this,this.VA);this.wY=new g.Wg(function(){});
g.c(this,this.wY);this.Kr=new ffY(S,function(A,k,P,b,N,h){CC(I,A,k,P,b,N,h)});
this.U=new g.C({K:"div",C:"iv-drawer",B:{id:"iv-drawer"},X:[{K:"div",C:"iv-drawer-header",B:{"aria-role":"heading"},X:[{K:"span",C:"iv-drawer-header-text"},{K:"button",kA:["iv-drawer-close-button","ytp-button"],B:{"aria-label":"Hide cards",tabindex:"0"}}]},{K:"div",C:"iv-drawer-content"}]});g.c(this,this.U);this.W=this.U.element;this.EV=new g.P8(this.U,330);g.c(this,this.EV);this.zk=g.sH("iv-drawer-header-text",this.W);this.L=g.sH("iv-drawer-content",this.W);this.addCueRange(0,S.videoData.lengthSeconds*
1E3,"",function(){I.b6&&sd(I,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(I.b6=I.Y)&&DP(I)});
this.xA=new g.Qv(this);g.c(this,this.xA);this.V.addEventListener("videodatachange",this.fh.bind(this))},tKn=function(e,K){K=K.data;
K.autoOpenMs&&e.addCueRange(K.autoOpenMs,0x8000000000000,"",function(){sd(e,"YOUTUBE_DRAWER_AUTO_OPEN")});
K.autoCloseMs&&e.addCueRange(K.autoCloseMs,0x8000000000000,"",function(){DP(e)});
var S=K.headerText;g.iD(e.zk,S);e.j&&e.j.setAttribute("title",S);K.eventId&&(e.eventId=K.eventId);e.QA=g.l8(K.trackingParams);e.N=g.l8(K.closeTrackingParams);e.Lv=g.l8(K.iconTrackingParams)},vVK=function(e,K){var S=K.cardId?K.cardId:"cr:"+e.Z,I=e.V.J().experiments.HY("enable_error_corrections_infocard_web_client");
if(!K.content&&K.teaser.simpleCardTeaserRenderer&&I){var A=K.teaser.simpleCardTeaserRenderer,k=K.icon?K.icon.infoCardIconRenderer:null;K={id:S,timestamp:e.Z,type:"simple",teaserText:g.uB(A.message),teaserDurationMs:Number(K.cueRanges[0].teaserDurationMs),startMs:Number(K.cueRanges[0].startCardActiveMs),autoOpen:!!K.autoOpen,sessionData:{},sponsored:!1,lB:{},MK:null,v2:A.trackingParams?g.l8(A.trackingParams):null,Lv:k&&k.trackingParams?g.l8(k.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
FU:null,title:"",customMessage:"",url:null,onClickCommand:A.onTapCommand||null};R0(e,K)}else{var P;if((P=K.content)==null?0:P.simpleCardContentRenderer){if(!K.cueRanges.length)return;k=(A=K.content)==null?void 0:A.simpleCardContentRenderer;A=K.teaser.simpleCardTeaserRenderer;var b=K.icon?K.icon.infoCardIconRenderer:null;K={id:S,timestamp:e.Z,type:"simple",teaserText:g.uB(A.message),teaserDurationMs:Number(K.cueRanges[0].teaserDurationMs),startMs:Number(K.cueRanges[0].startCardActiveMs),autoOpen:!!K.autoOpen,
sessionData:dl(e,S,K,k),sponsored:!1,lB:Od(k,A,k.command),MK:k.trackingParams?g.l8(k.trackingParams):null,v2:A.trackingParams?g.l8(A.trackingParams):null,Lv:b&&b.trackingParams?g.l8(b.trackingParams):null,imageUrl:zV(k.image.thumbnails,290).url,displayDomain:k.displayDomain?g.uB(k.displayDomain):null,showLinkIcon:!!k.showLinkIcon,FU:null,title:k.title?g.uB(k.title):"",customMessage:k.callToAction?g.uB(k.callToAction):"",url:g.Q(k.command,g.Z3).url?H$({pause_on_navigation:!e.context.videoData.isLivePlayback,
target:"new",value:g.Q(k.command,g.Z3).url}):null,onClickCommand:null};R0(e,K)}else{var N;if((N=K.content)==null?0:N.collaboratorInfoCardContentRenderer){if(!K.cueRanges.length)return;A=(k=K.content)==null?void 0:k.collaboratorInfoCardContentRenderer;k=K.teaser.simpleCardTeaserRenderer;b=K.icon?K.icon.infoCardIconRenderer:null;K={id:S,timestamp:e.Z,type:"collaborator",teaserText:g.uB(k.message),teaserDurationMs:Number(K.cueRanges[0].teaserDurationMs),startMs:Number(K.cueRanges[0].startCardActiveMs),
autoOpen:!!K.autoOpen,sessionData:dl(e,S,K,A),sponsored:!1,lB:Od(A,k,A.endpoint),MK:A.trackingParams?g.l8(A.trackingParams):null,v2:k.trackingParams?g.l8(k.trackingParams):null,Lv:b&&b.trackingParams?g.l8(b.trackingParams):null,channelId:g.Q(A.endpoint,g.vT).browseId,customMessage:A.customText?g.uB(A.customText):null,profileImageUrl:zV(A.channelAvatar.thumbnails,290).url,title:A.channelName?g.uB(A.channelName):"",metaInfo:[A.subscriberCountText?g.uB(A.subscriberCountText):""],url:H$({pause_on_navigation:!e.context.videoData.isLivePlayback,
target:"new",value:g.Q(A.endpoint,g.vT).canonicalBaseUrl?g.Q(A.endpoint,g.vT).canonicalBaseUrl:"/channel/"+g.Q(A.endpoint,g.vT).browseId}),onClickCommand:null};R0(e,K)}else{var h;if((h=K.content)==null?0:h.playlistInfoCardContentRenderer){if(!K.cueRanges.length)return;A=(b=K.content)==null?void 0:b.playlistInfoCardContentRenderer;k=K.teaser.simpleCardTeaserRenderer;b=K.icon?K.icon.infoCardIconRenderer:null;K={id:S,timestamp:e.Z,type:"playlist",teaserText:g.uB(k.message),teaserDurationMs:Number(K.cueRanges[0].teaserDurationMs),
startMs:Number(K.cueRanges[0].startCardActiveMs),autoOpen:!!K.autoOpen,sessionData:dl(e,S,K,A),sponsored:!1,lB:Od(A,k,A.action),MK:A.trackingParams?g.l8(A.trackingParams):null,v2:k.trackingParams?g.l8(k.trackingParams):null,Lv:b&&b.trackingParams?g.l8(b.trackingParams):null,j1:zV(A.playlistThumbnail.thumbnails,258).url,customMessage:A.customMessage?g.uB(A.customMessage):null,playlistVideoCount:g.uB(A.playlistVideoCount),title:A.playlistTitle?g.uB(A.playlistTitle):"",metaInfo:[A.channelName?g.uB(A.channelName):
"",A.videoCountText?g.uB(A.videoCountText):""],url:H$({pause_on_navigation:!e.context.videoData.isLivePlayback,target:"new",value:EVa(A.action)}),onClickCommand:null};R0(e,K)}else{var n;if((n=K.content)==null?0:n.videoInfoCardContentRenderer){if(!K.cueRanges.length)return;var V;A=(V=K.content)==null?void 0:V.videoInfoCardContentRenderer;k=K.teaser.simpleCardTeaserRenderer;b=K.icon?K.icon.infoCardIconRenderer:null;K={id:S,timestamp:e.Z,type:"video",teaserText:g.uB(k.message),teaserDurationMs:Number(K.cueRanges[0].teaserDurationMs),
startMs:Number(K.cueRanges[0].startCardActiveMs),autoOpen:!!K.autoOpen,sessionData:dl(e,S,K,A),sponsored:!1,lB:Od(A,k,A.action),MK:A.trackingParams?g.l8(A.trackingParams):null,v2:k.trackingParams?g.l8(k.trackingParams):null,Lv:b&&b.trackingParams?g.l8(b.trackingParams):null,j1:zV(A.videoThumbnail.thumbnails,258).url,videoDuration:A.lengthString?g.uB(A.lengthString):null,customMessage:A.customMessage?g.uB(A.customMessage):null,title:A.videoTitle?g.uB(A.videoTitle):"",metaInfo:[A.channelName?g.uB(A.channelName):
"",A.viewCountText?g.uB(A.viewCountText):""],isLiveNow:!!A.badge,url:H$({pause_on_navigation:!e.context.videoData.isLivePlayback,target:"new",value:EVa(A.action)}),onClickCommand:null};R0(e,K)}}}}}e.Z++},zV=function(e,K){for(var S=-1,I=-1,A=0;A<e.length;A++){if(e[A].height===K||e[A].width===290)return e[A];
((e[A].height||0)<K||(e[A].width||0)<290)&&(S<0||(e[S].height||0)<(e[A].height||0)||(e[S].width||0)<(e[A].width||0))?S=A:((e[A].height||0)>=K||(e[A].width||0)>=290)&&(I<0||(e[I].height||0)>(e[A].height||0)||(e[I].width||0)>(e[A].width||0))&&(I=A)}return e[I>=0?I:S]},dl=function(e,K,S,I){return{feature:S.feature?S.feature:"cards",
src_vid:e.context.videoData.videoId,annotation_id:K,ei:e.context.videoData.eventId||"",itct:I.trackingParams||""}},pvi=function(e,K){if(K=jVK(e,K))K===e.S&&(e.S=null),e.V.removeCueRange(K.SF.id),g.AC(K.PM),g.fi(e.cards,K),e.pA(),Fo(e)},sd=function(e,K,S){if(!e.Y){e.EV.show();
e.Cr=new g.Wg(function(){g.o3(e.context.V.getRootNode(),g.IE.IV_DRAWER_OPEN)},0);
e.Cr.start();e.xA.T(e.L,"mousewheel",function(P){e.VA.start();P.preventDefault();P=P||window.event;var b=0;P.type=="MozMousePixelScroll"?b=0==(P.axis==P.HORIZONTAL_AXIS)?P.detail:0:window.opera?b=P.detail:b=P.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?P.wheelDeltaY/-30:P.wheelDeltaY/-1.2:P.wheelDelta/-1.6:P.wheelDeltaY/-3;if(P=b)e.L.scrollTop+=P});
e.Y=!0;var I=g.jB();I&&e.QA&&e.N&&g.op(I,[e.QA,e.N]);K={TRIGGER_TYPE:K};for(var A=g.f(e.cards),k=A.next();!k.done;k=A.next())k=k.value,k.nV||(k.nV=!0,xpD(e.context.logger,k.SF.lB.CK,K)),I&&g.op(I,[k.SF.MK]);uV(e.V);S&&(e.G=new g.Wg(function(){e.RS=e.j;e.PN.focus()},330),e.G.start())}},DP=function(e){e.Y&&(e.EV.hide(),g.UI(e.xA),g.b1(e.context.V.getRootNode(),g.IE.IV_DRAWER_OPEN),e.Y=!1,uV(e.V),e.G&&e.G.stop(),e.G=new g.Wg(function(){e.RS&&(e.RS.focus(),e.RS=null)},330),e.G.start())},Gm4=function(e){g.Mr(e.yH(),
[g.IE.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.QA(e.V,e.W,5);e.ji();e.j=g.sH("ytp-cards-button",e.V.getRootNode());e.PN=g.sH("iv-drawer-close-button",e.W);e.isInitialized=!0},UpS=function(e){e.zA.push(g.M1("iv-teaser-shown",e.iW,e));
e.zA.push(g.M1("iv-teaser-hidden",e.A6A,e));e.zA.push(g.M1("iv-teaser-clicked",e.It,e));e.L8=!0},ylu=function(e,K){var S;
return K.onClickCommand&&((S=g.Q(K.onClickCommand,g.bee))==null?void 0:S.targetId)==="engagement-panel-error-corrections"?(e.rY=K,!0):!1},Bdi=function(e,K){e.rY=K;
var S=e.V.getVideoData();if(!S)return!1;S=g.p1(S);if(S==null?0:S.markersMap)for(var I,A=0;((I=S)==null?void 0:I.markersMap.length)>A;A++){var k=void 0,P=(k=S)==null?void 0:k.markersMap[A];if(P.key==="ERROR_CORRECTION_MARKERS"&&(k=void 0,(P=(k=P.value)==null?void 0:k.markers)&&P.length>0))return I=void 0,K.startMs=((I=g.Q(P[0],g.Q0C))==null?void 0:I.timeRangeStartMillis)||0,e.rY=null,!0}return!1},R0=function(e,K){if(!ylu(e,K)||Bdi(e,K)){var S=afi(e,K);
if(S){var I={SF:K,PM:S.element,nV:!1};if(K.onClickCommand)e.V.D("web_infocards_teaser_show_logging_fix")&&(e.L8||UpS(e),pvi(e,K.id),S=e.findLastIndex(I),g.lu(e.cards,S,0,I));else{e.isInitialized||Gm4(e);pvi(e,K.id);var A=e.findLastIndex(I);g.lu(e.cards,A,0,I);S.As(e.L,A);e.pA()}K.autoOpen?e.addCueRange(K.startMs,0x8000000000000,K.id,function(){e.Y||(e.S=I,Fo(e),H8e(e,I),sd(e,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(S=e.context.V.getCurrentTime()*1E3,S<5E3&&S>K.startMs&&cl4(e,I),e.addCueRange(K.startMs,
K.startMs+1,K.id,function(){cl4(e,I)}),Fo(e))}}},afi=function(e,K){switch(K.type){case "simple":e=e.Kr;
var S=K.displayDomain?{K:"div",C:"iv-card-image-text",YA:K.displayDomain}:void 0;var I=mp4(K);S={K:"div",kA:["iv-card"],X:[{K:"a",C:"iv-click-target",B:{href:K.url?a0(K.url)||"":""},X:[Qc(K.imageUrl,S),{K:"div",C:"iv-card-content",X:[c$("h2",void 0,K.title),I]}]}]};S=new g.C(S);ZP(e,g.Ce("iv-click-target",S.element),K,K.url);K=S;break;case "collaborator":e=e.Kr;S={K:"div",kA:["iv-card","iv-card-channel"],X:[{K:"a",kA:["iv-click-target"],B:{href:a0(K.url)||"","data-ytid":K.channelId},X:[Qc(K.profileImageUrl),
{K:"div",C:"iv-card-content",X:[$pu(K),{K:"h2",C:"iv-card-primary-link",YA:K.title},uAi(K)]}]}]};S=new g.C(S);ZP(e,g.Ce("iv-click-target",S.element),K,K.url);K=S;break;case "playlist":e=e.Kr;S={K:"div",kA:["iv-card","iv-card-playlist"],X:[{K:"a",C:"iv-click-target",B:{href:a0(K.url)||""},X:[Qc(K.j1,{K:"div",C:"iv-card-image-overlay",X:[{K:"span",C:"iv-card-playlist-video-count",YA:K.playlistVideoCount}]}),{K:"div",C:"iv-card-content",X:[$pu(K),c$("h2","iv-card-primary-link",K.title),uAi(K)]}]}]};
S=new g.C(S);ZP(e,g.Ce("iv-click-target",S.element),K,K.url);K=S;break;case "productListing":e=e.Kr;var A=K.offers.length!=0;S=["iv-card"];I="";var k=mp4(K);A&&(S.push("iv-card-product-listing"),I="iv-card-primary-link",k=K.offers[0],A=[],k.price&&A.push({K:"div",C:"iv-card-offer-price",YA:k.price}),k.merchant&&A.push({K:"div",C:"iv-card-offer-merchant",YA:k.merchant}),k={K:"div",X:A});A=K.url?a0(K.url)||"":"";S={K:"div",kA:S,B:{tabindex:"0"},X:[{K:"a",kA:["iv-card-image","iv-click-target"],B:{style:"background-image: url("+
K.imageUrl+");",href:A,"aria-hidden":"true",tabindex:"-1"}},{K:"div",C:"iv-card-content",X:[K.sponsored?{K:"div",C:"iv-card-sponsored",X:["Sponsored",{K:"div",C:"iv-ad-info-container",X:[{K:"div",C:"iv-ad-info",YA:"{{adInfo}}"},{K:"div",C:"iv-ad-info-icon-container",X:[{K:"div",C:"iv-ad-info-icon"},{K:"div",C:"iv-ad-info-callout"}]}]}]}:"",{K:"a",C:"iv-click-target",B:{href:A},X:[c$("h2",I,K.title),k]}]}]};S=new g.C(S);I=g.W3("span");g.iD(I,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
S.SX(I,"adInfo");ZP(e,g.Ce("iv-click-target",S.element),K,K.url);K=S;break;case "video":e=e.Kr;I=K.videoDuration?{K:"span",C:"iv-card-video-duration",YA:K.videoDuration}:void 0;k=K.isLiveNow?{K:"span",kA:["yt-badge","yt-badge-live"],YA:"LIVE NOW"}:null;A={K:"div",kA:["iv-card","iv-card-video"],X:[{K:"a",C:"iv-click-target",B:{href:((S=K.url)==null?void 0:a0(S))||""},X:[Qc(K.j1,I),{K:"div",C:"iv-card-content",X:[$pu(K),c$("h2","iv-card-primary-link",K.title),uAi(K),k]}]}]};S=new g.C(A);ZP(e,g.Ce("iv-click-target",
S.element),K,K.url);K=S;break;default:return null}return K},QV6=function(e){if(e.S)return e.S.SF.type==="productListing";
if(e.V.D("enable_wn_infocards")){var K;return!((K=e.cards)==null||!K.length)&&g.OQ(e.cards,function(S){return S.SF.type==="productListing"})}return g.OQ(e.cards,function(S){return S.SF.type==="productListing"})},Fo=function(e){g.np(e.V.getRootNode(),"ytp-cards-shopping-active",QV6(e))},cl4=function(e,K){if(!g.g1(e.V.getRootNode(),"ytp-cards-teaser-shown")){if(e.S!==K){var S=g.jB(),I=e.S?e.S.SF.Lv:e.Lv;
S&&I&&g.Mo(S,[I]);e.S=K;Fo(e)}if(S=e.isInitialized)S=e.yH().style.display=="none";S||(S=e.context.V.getPlayerState(),I=S===0&&e.context.V.getCurrentTime()===0,S=!(S===1||S===3||I));S||K.SF.teaserDurationMs&&e.V.Ql(!0,{teaserText:K.SF.teaserText,durationMs:K.SF.teaserDurationMs,onClickCommand:K.SF.onClickCommand});e.wY.isActive()||((!e.Y||!e.VA.isActive()&&e.eG)&&H8e(e,K),e.wY.start(910+K.SF.teaserDurationMs))}},H8e=function(e,K){e.U.rN?(K=new Ed([0,
e.L.scrollTop],[0,K.PM.offsetTop],600,DWa),e.context.Y.listen(K,"animate",function(S){e.L.scrollTop=S.y}),e.context.Y.listen(K,"finish",function(S){e.L.scrollTop=S.y}),K.play()):(e.U.S9(!0),e.L.scrollTop=K.PM.offsetTop,e.U.S9(!1))},W$=function(e){return e.S&&e.S.SF?e.S.SF:e.cards[0]&&e.cards[0].SF?e.cards[0].SF:null},jVK=function(e,K){return g.we(e.cards,function(S){return S.SF.id===K})},e9=function(e,K,S){rl.call(this,e,K);
this.annotation=S;this.isActive=!1},Z8K=function(e){var K=e.annotation.data;
"start_ms"in K&&"end_ms"in K&&e.addCueRange(Number(K.start_ms),Number(K.end_ms),e.annotation.id,function(){e.show()},function(){e.hide()})},KU=function(e,K,S){e9.call(this,e,K,S);
this.L=null;this.N=!1;this.Y=null;this.W=!1;this.S=this.Z=this.G=null},rlK=function(e,K){var S=S===void 0?0:S;
var I=aJD(K).width;g.rm(K,I);S=new OmK(K,[I,K.offsetTop],[I-I-S,K.offsetTop],200,shS);g.c(e,S);e.context.Y.listen(S,"begin",function(){g.dm(K,!0)});
S.play()},sVS=function(e,K){if(K.channel_name){var S=e.createElement({K:"div",
kA:["iv-branding-context-name"],YA:K.channel_name}),I=e.createElement({K:"div",kA:["iv-branding-context-subscribe"]}),A=K.standalone_subscribe_button_data;A&&(e.S=new g.OZ(A.subscribeText,A.subscribeCount,A.unsubscribeText,A.unsubscribeCount,!!A.enabled,!!A.classic,K.channel_id,!!A.subscribed,A.feature,K.session_data.itct,e.context.V,!1),e.S.As(I));var k=e.createElement({K:"div",kA:["iv-branding-context-subscribe-caret"]}),P=e.createElement({K:"div",kA:["branding-context-container-inner"]});P.appendChild(k);
P.appendChild(S);P.appendChild(I);g.dm(P,!1);var b=e.createElement({K:"div",kA:["branding-context-container-outer"]});b.appendChild(P);g.Bn(b,"right",K.image_width+"px");g.Ko(e.yH(),b);e.Y=new g.Wg(function(){C_K(e,P,b)},500);
g.c(e,e.Y);e.context.S.listen(e.yH(),"mouseover",function(){O8n(e,P,b,k,K.image_height)});
e.context.S.listen(e.yH(),"mouseout",function(){e.Y.start()})}},O8n=function(e,K,S,I,A){e.Y.stop();
if(!e.W){var k=g.Ry(K);e.S||(K.style.width=g.Zy(k.width,!0),S.style.width=g.Zy(k.width,!0));g.Bn(I,"top",k.height-Math.max(Math.min(k.height,A)/2+10,20)+"px");g.Bn(I,"right","1px");e.W=!0;g.dm(K,!0);e.G=new g.Wg(function(){g.o3(this.yH(),"iv-branding-active")},0,e);
e.G.start()}},C_K=function(e,K,S){g.b1(e.yH(),"iv-branding-active");
e.Z=new g.Wg(function(){g.dm(K,!1);e.S||(S.style.width=g.Zy(0,!0))},250);
e.Z.start();e.W=!1},Dpa=function(e,K,S,I,A,k,P){this.S=e;
this.Y=K;this.PY=S;this.videoData=I;this.logger=A;this.V=k;this.L=P},Rt6=function(e,K,S){e9.call(this,e,K,S);
var I=this;this.j=this.isCollapsed=this.U=!1;this.Z=5E3;this.L=this.Y=this.S=this.W=null;this.N=this.createElement({K:"div",kA:["iv-promo-contents"]});this.G=new g.Wg(function(){I.S.setAttribute("aria-hidden","true");g.dm(I.Y,!1);g.dm(I.L,!0)},700,this);
g.c(this,this.G)},ztu=function(e){var K=e.annotation.data;
if(e.annotation.style==="cta")var S=6;else if(e.annotation.style==="video"||e.annotation.style==="playlist")S=7;e.Z=K.collapsedelay_ms||e.Z;var I=["iv-promo","iv-promo-inactive"];e.yH().setAttribute("aria-hidden","true");e.yH().setAttribute("aria-label","Promotion");e.yH().tabIndex=0;var A=e.annotation.uV(),k=K.image_url;if(k){var P=e.createElement({K:"div",kA:["iv-promo-img","iv-click-target"]});k=e.createElement({K:"img",B:{src:k,"aria-hidden":"true"}});P.appendChild(k);K.video_duration&&!K.is_live?
(k=e.createElement({K:"span",C:"iv-promo-video-duration",YA:K.video_duration}),P.appendChild(k)):K.playlist_length&&(k=e.createElement({K:"span",C:"iv-promo-playlist-length",YA:K.playlist_length.toString()}),P.appendChild(k));A&&CC(e,P,A,e.annotation.id,K.session_data,void 0,S)}A?(k=e.createElement({K:"a",C:"iv-promo-txt"}),g.z6(k,a0(A)),e.S=k):e.S=e.createElement({K:"div",C:"iv-promo-txt"});switch(e.annotation.style){case "cta":case "website":var b=e.createElement({K:"p",X:[{K:"strong",YA:K.text_line_1}]});
var N=e.createElement({K:"p",X:[{K:"span",C:"iv-promo-link",YA:K.text_line_2}]});if(k=K.text_line_3){I.push("iv-promo-website-card-cta-redesign");var h=e.createElement({K:"button",kA:["iv-promo-round-expand-icon","ytp-button"]});k=e.createElement({K:"button",kA:["iv-button","iv-promo-button"],X:[{K:"span",C:"iv-button-content",YA:k}]});var n=e.createElement({K:"div",C:"iv-promo-button-container"});n.appendChild(k);A&&CC(e,e.yH(),A,e.annotation.id,K.session_data,void 0,S)}g.o3(e.S,"iv-click-target");
A&&CC(e,e.S,A,e.annotation.id,K.session_data,void 0,S);break;case "playlist":case "video":b=e.createElement({K:"p",X:[{K:"span",YA:K.text_line_1}]}),N=e.createElement({K:"p",X:[{K:"strong",YA:K.text_line_2}]}),K.is_live&&(b=N,N=e.createElement({K:"span",kA:["yt-badge","iv-promo-badge-live"],YA:"LIVE NOW"})),g.o3(e.S,"iv-click-target"),A&&CC(e,e.S,A,e.annotation.id,K.session_data,void 0,S),I.push("iv-promo-video")}b&&e.S.appendChild(b);N&&e.S.appendChild(N);e.N.appendChild(e.S);n&&e.N.appendChild(n);
S=e.createElement({K:"div",C:"iv-promo-actions"});e.L=e.createElement({K:"button",kA:["iv-promo-expand","ytp-button"]});e.L.title="Expand";e.context.S.listen(e.L,"click",function(V){dp4(e,5E3,V)});
S.appendChild(e.L);g.dm(e.L,!1);e.context.S.listen(e.yH(),"mouseover",e.br_,e);e.context.S.listen(e.yH(),"mouseout",e.qVY,e);e.context.S.listen(e.yH(),"touchend",function(V){dp4(e,5E3,V)});
e.Y=e.createElement({K:"button",kA:["iv-promo-close","ytp-button"]});e.Y.title="Close";e.context.S.listen(e.Y,"click",e.annotation.style==="cta"&&K.text_line_3?e.YVy:e.Lys,e);S.appendChild(e.Y);g.Mr(e.yH(),I);P&&(g.Ko(e.yH(),P),h&&P.appendChild(h));g.Ko(e.yH(),e.N);g.Ko(e.yH(),S)},dp4=function(e,K,S){S.stopPropagation();
F3a(e);W3S(e,K);e.S.focus()},e5a=function(e){e.isCollapsed||e.j||e.W||(g.o3(e.yH(),"iv-promo-collapsed"),e.isCollapsed=!0,e.G.start())},F3a=function(e){e.G.stop();
e.isCollapsed&&(g.Nr(e.yH(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),e.isCollapsed=!1,e.S&&e.S.removeAttribute("aria-hidden"),g.dm(e.L,!1),g.dm(e.Y,!0))},W3S=function(e,K){e.W||(e.W=g.Hm(function(){Kvu(this);
e5a(this)},K,e))},Kvu=function(e){e.W&&(g.DN.clearTimeout(e.W),e.W=null)},SGK=function(e){this.V=e},xpD=function(e,K,S){K&&(S?S9(e,K.map(function(I){return g.GK(I,S)})):S9(e,K))},S9=function(e,K,S,I){var A=1,k=void 0,P=-1;
if(S){var b=!1;k=function(){A--;A||b||(clearTimeout(P),b=!0,S())};
P=setTimeout(function(){b=!0;S()},1E3)}K=g.f(K||[]);
for(var N=K.next();!N.done;N=K.next())N=N.value,A++,g.OS(N,k);I&&(A++,I!==0&&e.V.sendVideoStatsEngageEvent(I,k))},IXK=function(e){g.NK.call(this,e);
var K=this;this.zA=this.j=!1;this.loadNumber=0;this.Z={};this.logger=new SGK(this.player);this.W=new g.Qv(this);this.G=this.N=null;this.events=new g.Qv(this);this.k6=this.U=this.S=null;this.rY=[];g.c(this,this.W);this.W.T(this.player,"onVideoAreaChange",function(){K.publish("onVideoAreaChange")});
this.W.T(this.player,"onHideControls",function(){K.publish("onHideControls")});
this.W.T(this.player,"onShowControls",function(){K.publish("onShowControls")});
this.W.T(this.player,"resize",function(I){K.publish("resize",I)});
this.W.T(this.player,"presentingplayerstatechange",function(I){K.publish("presentingplayerstatechange",I)});
this.subscribe("presentingplayerstatechange",this.cz,this);this.subscribe("resize",this.L1,this);this.player.J().RS.subscribe("vast_info_card_add",this.UY,this);g.c(this,this.events);this.Kr=this.createElement({K:"div",C:"video-custom-annotations"});this.L=new g.C({K:"div",kA:["ytp-player-content","ytp-iv-player-content"]});g.c(this,this.L);g.QA(this.player,this.L.element,4);this.L.hide();this.Y=new g.C({K:"div",kA:["ytp-iv-video-content"]});g.c(this,this.Y);e=this.createElement({K:"div",C:"video-annotations"});
e.appendChild(this.Kr);this.Y.element.appendChild(e);this.GC()&&this.load();var S=this.createElement({K:"style"});(g.rK("HEAD")[0]||document.body).appendChild(S);this.addOnDisposeCallback(function(){g.AC(S)});
if(e=S.sheet)e.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),e.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),e.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),e.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),e.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),e.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),e.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),e.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),e.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),e.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},A9k=function(e){e=e.createElement({K:"div",
kA:["annotation","annotation-type-custom"]});g.dm(e,!1);return e},k04=function(e,K){K=!K.isCued()&&!g.D(K,1024);
e.L.S9(K);e.Y.S9(K)},ixe=function(e,K,S){e.j=!0;
e.G=g.vO(K,S)},PWK=function(e,K){for(var S={},I=g.f(K.attributes),A=I.next();!A.done;A=I.next())A=A.value,S[A.name]=A.nodeValue;
for(I=0;I<K.childNodes.length;I++)if(A=K.childNodes[I],g.Ki(A)&&A.nodeType==1){if(S[A.tagName])var k=S[A.tagName];else if(A.tagName==="data"){A.childNodes.length>0&&(k=A.childNodes[0].nodeValue,S[A.tagName]=typeof k==="string"?k.trim():k);continue}else k=[],S[A.tagName]=k;A&&A.tagName==="TEXT"?A.childNodes.length===1&&A.childNodes[0].nodeType===3?k.push(A.childNodes[0].nodeValue):k.push(""):A&&k.push(PWK(e,A))}return S},bxk=function(e){var K=g.y(e.player.getVideoData());
if(K.Js){var S=e.player.J().RS.get(K.videoId);if(S){var I={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(A,k,P){A=e.loadNumber;k=K.videoId;e.loaded&&e.loadNumber===A&&e.player.getVideoData().videoId===k&&(P=g.X8(P)&&P.responseXML?P.responseXML:null)&&gPu(e,P)}};
g.Ps()&&(I.onFinish=oP4(e,I.onFinish));I.postParams={ic_only:"1"};Mma(I,S);e.j=!0;g.vO(K.Js,I)}}},Mma=function(e,K){e.method="POST";
e.postParams=e.postParams||{};K.g$&&(e.postParams.ic_coll=K.g$);K.p6&&(e.postParams.ic_xml=K.p6);K.wc&&(e.postParams.ic_track=K.wc)},Nji=function(e){var K=new g.C({K:"div"});
g.dm(K.element,!1);var S=new lfK(e.player,K.element,Is(e));g.c(S,K);K.As(e.L.element);S.l4();return S},nPY=function(e,K){var S,I;
if(K=(S=K.getWatchNextResponse())==null?void 0:(I=S.cards)==null?void 0:I.cardCollectionRenderer)e.zA=!0,h54(e,K),K.headerText&&e.k6&&(S=g.uB(K.headerText),e.k6.setAttribute("title",S))},Is=function(e){if(!e.U){var K=new Rlu(e);
g.c(e,K);var S=new g.XT(e);g.c(e,S);e.U=new Dpa(K,S,e.player.J(),e.player.getVideoData(),e.logger,e.player,e.xv)}return e.U},gPu=function(e,K){var S=!1,I=K.getElementsByTagName("annotations");
if(I&&!(I.length<1)&&(I=I[0].getAttribute("itct"))){var A=g.jB();if(A){var k=g.vl();k&&g.I5(g.FV)(void 0,A,k,[g.l8(I)])}}K=K.getElementsByTagName("annotation");for(I=0;I<K.length;I++){k=PWK(e,K[I]);A=null;try{if(k){var P=k.id,b=/.+/;var N=typeof P==="string"&&b!=null&&P!=null&&P.match(b)?P:"";var h=B$(k.type,Vmi),n=B$(k.style,wPK),V=b8a(k.data),w=V.length!==0?JSON.parse(V):{};var T=k.action;k=Td4;if(T==null)var Y=null;else if(g.eY(T)){b=[];for(var u=g.f(T),L=u.next();!L.done;L=u.next()){var q=k(L.value);
q&&b.push(q)}Y=b}else{var E=k(T);Y=E?[E]:[]}A=N&&h?new Yq4(N,h,n,Y,w):null}else A=null}catch(SO){}if(A)if(A.type==="branding"||A.type==="promotion"){k=e;b=A;var t=A9k(k),U=null;switch(b.type){case "branding":if(k.player.J().Kb)break;k.L.element.appendChild(t);U=new KU(t,Is(k),b);break;case "promotion":g.QA(k.player,t,4),U=new Rt6(t,Is(k),b)}U&&U.l4();if(k=U)g.c(e,k),e.Z[A.id]=k}else if(A.type==="card"||A.type==="drawer"){e.S||(e.S=Nji(e),g.c(e,e.S));if(A.type==="card"){t=e.S;var H=(S=A)&&S.data&&
S.data.card_type;A=S.data;if(H)switch(k=A.tracking||{},k={CK:k.impression,click:k.click,close:k.close,oT:k.teaser_impression,md:k.teaser_click},b=A.tracking_params||{},U=null,H){case "collaborator":S={id:S.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,lB:k,MK:b.card?g.l8(b.card):null,v2:b.teaser?g.l8(b.teaser):null,Lv:b.icon?g.l8(b.icon):
null,channelId:A.channel_id,customMessage:A.custom_message?A.custom_message:null,profileImageUrl:A.image_url,title:A.title,metaInfo:A.meta_info,url:H$({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url}),onClickCommand:null};R0(t,S);break;case "playlist":S={id:S.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,lB:k,
MK:b.card?g.l8(b.card):null,v2:b.teaser?g.l8(b.teaser):null,Lv:b.icon?g.l8(b.icon):null,j1:A.image_url,playlistVideoCount:A.playlist_video_count,customMessage:A.custom_message?A.custom_message:null,title:A.title,metaInfo:A.meta_info,url:g.y(H$({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url})),onClickCommand:null};R0(t,S);break;case "productListing":A.signin_url&&(U=H$({target:"current",value:A.signin_url}));H=[];for(var R=A.offers||[],O=0;O<R.length;O++)H.push(new L3u(g.XM(R[O].merchant),
g.XM(R[O].price)));S={id:S.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,lB:k,MK:b.card?g.l8(b.card):null,v2:b.teaser?g.l8(b.teaser):null,Lv:b.icon?g.l8(b.icon):null,imageUrl:A.image_url,displayDomain:A.display_domain?A.display_domain:null,showLinkIcon:!!A.show_link_icon,FU:A.button_icon_url?A.button_icon_url:null,title:A.title,customMessage:A.custom_message?
A.custom_message:null,url:g.y(H$({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url})),YzP:U,LSL:A.signin_title?A.signin_title:void 0,gyL:A.signin_message?A.signin_message:void 0,offers:H,onClickCommand:null};R0(t,S);break;case "simple":S={id:S.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,lB:k,MK:b.card?g.l8(b.card):
null,v2:b.teaser?g.l8(b.teaser):null,Lv:b.icon?g.l8(b.icon):null,imageUrl:A.image_url,displayDomain:A.display_domain?A.display_domain:null,showLinkIcon:!!A.show_link_icon,FU:A.button_icon_url?A.button_icon_url:null,title:A.title,customMessage:A.custom_message?A.custom_message:null,url:g.y(H$({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url})),onClickCommand:null};R0(t,S);break;case "video":S={id:S.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,
startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,lB:k,MK:b.card?g.l8(b.card):null,v2:b.teaser?g.l8(b.teaser):null,Lv:b.icon?g.l8(b.icon):null,j1:A.image_url,videoDuration:A.video_duration||null,customMessage:A.custom_message?A.custom_message:null,title:A.title,metaInfo:A.meta_info,isLiveNow:!!A.is_live_now,url:g.y(H$({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url})),onClickCommand:null},R0(t,S)}}else tKn(e.S,A);S=!0}}S&&
(uV(e.player),e.L1())},h54=function(e,K){var S=!1;
e.S||(e.S=Nji(e),g.c(e,e.S));for(var I=g.f(K.cards||[]),A=I.next();!A.done;A=I.next())A=A.value,A.cardRenderer&&(vVK(e.S,A.cardRenderer),S=!0);if(S){var k;(k=e.player.getVideoData())!=null&&g.BT(k)||(S=e.S,I=K.headerText?g.uB(K.headerText):"",g.iD(S.zk,I),S.j&&S.j.setAttribute("title",I),S.context.videoData.eventId&&(S.eventId=S.context.videoData.eventId),S.QA=K.trackingParams?g.l8(K.trackingParams):null,S.N=K.closeButton.infoCardIconRenderer.trackingParams?g.l8(K.closeButton.infoCardIconRenderer.trackingParams):
null,S.Lv=K.icon.infoCardIconRenderer.trackingParams?g.l8(K.icon.infoCardIconRenderer.trackingParams):null,e.L1());uV(e.player)}},Tja=function(e,K,S,I,A){if(!e.player.J().Kb){var k=[];
K.navigationEndpoint&&g.Q(K.navigationEndpoint,g.vT)&&g.Q(K.navigationEndpoint,g.vT).browseId&&k.push(new nVe("openUrl","click",new Ndk("/channel/"+g.Q(K.navigationEndpoint,g.vT).browseId,"new",!0,!0)));var P=K.watermark.thumbnails[0];I={channel_name:K.channelName,end_ms:K.endTimeMs,image_height:P.height,image_type:1,image_url:P.url,image_width:P.width,is_mobile:!1,session_data:{annotation_id:S,ei:A,feature:"iv",itct:K.trackingParams,src_vid:I},start_ms:K.startTimeMs};if(K.subscribeButton&&g.Q(K.subscribeButton,
g.jb)){I.channel_id=g.Q(K.subscribeButton,g.jb).channelId;var b;K=g.Q(K.subscribeButton,g.jb);P=A=null;K.subscribed?(K.subscriberCountWithUnsubscribeText&&(A=g.uB(K.subscriberCountWithUnsubscribeText)),K.subscriberCountText&&(P=g.uB(K.subscriberCountText))):(K.subscriberCountText&&(A=g.uB(K.subscriberCountText)),K.subscriberCountWithSubscribeText&&(P=g.uB(K.subscriberCountWithSubscribeText)));var N,h=((N=g.Q((b=K.signInEndpoint)==null?void 0:b.commandMetadata,g.Vg))==null?void 0:N.url)||"";b={subscribeText:g.uB(K.unsubscribedButtonText),
subscribeCount:A||"",unsubscribeText:g.uB(K.subscribedButtonText),unsubscribeCount:P||"",enabled:K.enabled||!1,classic:!1,subscribed:K.subscribed||!1,feature:"iv",signInUrl:h};I.standalone_subscribe_button_data=b}k=new Yq4(S,"branding","branding",k,I);b=A9k(e);e.L.element.appendChild(b);k=new KU(b,Is(e),k);k.l4();g.c(k,k);e.Z[S]=k}},oP4=function(e,K){return function(){var S=g.ye.apply(0,arguments);
e.DL()||e.rY.push(g.r2.P_(function(){K.apply(null,g.m(S))}))}},YGK=function(e){return e==="annotation-editor"||e==="live-dashboard"};
g.xY.prototype.Ql=g.il(45,function(e,K){var S=g.qK(this.A6());S&&S.Ql(e,K)});
var LC={},Jq=null;g.oa(Ed,g.VB);g.M=Ed.prototype;g.M.getDuration=function(){return this.duration};
g.M.play=function(e){if(e||this.S==0)this.progress=0,this.coords=this.L;else if(this.isPlaying())return!1;qV(this);this.startTime=e=g.PS();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.W=this.startTime;this.progress||this.O2();this.O6("play");this.isPaused()&&this.O6("resume");this.S=1;var K=g.Ia(this);K in LC||(LC[K]=this);QhD();Zm6(this,e);return!0};
g.M.stop=function(e){qV(this);this.S=0;e&&(this.progress=1);r1e(this,this.progress);this.onStop();this.cg()};
g.M.pause=function(){this.isPlaying()&&(qV(this),this.S=-1,this.O6("pause"))};
g.M.Lr=function(){this.S==0||this.stop(!1);this.O6("destroy");Ed.QW.Lr.call(this)};
g.M.destroy=function(){this.dispose()};
g.M.Cd=function(){this.O6("animate")};
g.M.O6=function(e){this.dispatchEvent(new CAa(e,this))};
g.oa(CAa,g.FG);g.oa(lV,Ed);lV.prototype.Y=function(){};
lV.prototype.Cd=function(){this.Y();lV.QW.Cd.call(this)};
lV.prototype.cg=function(){this.Y();lV.QW.cg.call(this)};
lV.prototype.O2=function(){this.Y();lV.QW.O2.call(this)};
g.oa(OmK,lV);OmK.prototype.Y=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.X(Rlu,g.B);g.M=Rlu.prototype;g.M.listen=function(e,K,S,I){S=(0,g.kK)(S,I||this.L);e=g.lX(e,K,S);this.S.push(e);return e};
g.M.cq=function(e,K,S,I){S=(0,g.kK)(S,I||this.L);e=Hmk(e,K,S);this.S.push(e);return e};
g.M.yx=function(e){g.tf(e);g.fi(this.S,e)};
g.M.removeAll=function(){g.tf(this.S);this.S.length=0};
g.M.Lr=function(){this.removeAll();g.B.prototype.Lr.call(this)};g.X(FAD,g.NK);g.M=FAD.prototype;g.M.load=function(){g.NK.prototype.load.call(this);if(!jP(this)){var e=g.nnN(this.player.getVideoData());e?(e=zle(e,WAa(this)),pC(this,e,!1)):etK(this)}};
g.M.unload=function(){pC(this,null);this.W&&(this.W.abort(),this.W=null);g.NK.prototype.unload.call(this)};
g.M.Ke=function(e,K){return jP(this)?e==="loadCustomEndscreenRenderer"?(e=zle(K,"new"),pC(this,e),!0):null:null};
g.M.getOptions=function(){return jP(this)?["loadCustomEndscreenRenderer"]:[]};
g.M.dN=function(){if(this.endscreen&&this.endscreen.elements){var e=this.player.getVideoContentRect();if(e&&e.width!==0&&e.height!==0){var K=this.player.getPlayerSize();if(K&&K.width!==0&&K.height!==0){var S=e.width/e.height;var I=0;for(var A=-1,k=0;k<XPu.length;k++){var P=Math.abs(K.width-XPu[k]);if(A===-1||I>=P)A=k,I=P}I=fXK[A];this.Y&&g.Bn(this.Y.element,"outline-width",Math.max(K.width,K.height)+"px");for(K=0;K<this.endscreen.elements.length;++K)if(k=this.endscreen.elements[K].id,A=this.L[k],
P=this.Z[k],A&&P){var b=P.width*S/P.aspectRatio,N=Math.round(P.width*e.width);k=Math.round(b*e.height);var h=e.left+Math.round(P.left*e.width),n=e.top+Math.round(P.top*e.height);g.Dy(A.element,N,k);g.rm(A.element,h,n);g.Nr(A.element,$Cu);N>256||k>256?g.o3(A.element,"ytp-ce-large-round"):N>96||k>96?g.o3(A.element,"ytp-ce-medium-round"):g.o3(A.element,"ytp-ce-small-round");g.Nr(A.element,u9Y);N=P.left+P.width/2;P=P.top+b/2;g.o3(A.element,N<=.5&&P<=.5?"ytp-ce-top-left-quad":N>.5&&P<=.5?"ytp-ce-top-right-quad":
N<=.5&&P>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Nr(A.element,fXK);g.o3(A.element,I);(A=g.OH(document,"div","ytp-ce-expanding-overlay-body",A.element)[0])&&g.Bn(A,"height",k+"px")}}}}};
g.M.onCueRangeEnter=function(e){if(this.endscreen)if(e.getId()==="ytp-ce-in-endscreen")yc(this,this.endscreen.impressionUrls),(e=g.jB())&&this.endscreen.visualElement&&g.gv(e,this.endscreen.visualElement),this.S&&(g.o3(this.S,"ytp-ce-element-show"),this.S.removeAttribute("aria-hidden"),this.player.Vk()?g.o3(this.S,"ytp-ce-hide-button-lower"):g.b1(this.S,"ytp-ce-hide-button-lower"));else{e=e.getId().substring(15);var K=this.L[e],S=this.Z[e];g.o3(K.element,"ytp-ce-element-show");K.element.removeAttribute("aria-hidden");
K=this.player.getRootNode();g.o3(K,"ytp-ce-shown");yc(this,S.impressionUrls);(K=g.jB())&&g.gv(K,S.visualElement);this.player.J().N&&this.player.Xt("endscreenelementshown",e)}};
g.M.onCueRangeExit=function(e){if(e.getId()==="ytp-ce-in-endscreen")this.S&&(g.b1(this.S,"ytp-ce-element-show"),this.S.setAttribute("aria-hidden","true"));else{e=e.getId().substring(15);var K=this.L[e];g.b1(K.element,"ytp-ce-element-show");K.element.setAttribute("aria-hidden","true");K=this.player.getRootNode();g.b1(K,"ytp-ce-shown");this.player.J().N&&this.player.Xt("endscreenelementhidden",e)}};
g.M.O3_=function(e){var K=this;e.target===window&&(new g.Wg(function(){for(var S=g.f(Object.values(K.L)),I=S.next();!I.done;I=S.next())g.Nr(I.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.M.S9=function(e){for(var K=g.f(Object.values(this.L)),S=K.next();!S.done;S=K.next())S=S.value,e?S.element.setAttribute("hidden",""):S.element.removeAttribute("hidden")};
g.M.YbA=function(e){this.S&&this.player.getRootNode().removeChild(this.S);e&&(g.o3(e,"ytp-ce-hide-button-container"),this.S=e,g.QA(this.player,this.S,4))};
var XPu=[346,426,470,506,570,640,853,1280,1920],fXK="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),u9Y=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],$Cu=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var htu={bsr:"current",HBV:"new"};var VKe={CLOSE:"close",PQY:"openUrl",SUBSCRIBE:"subscribe"},wv6={X_y:"click",CLOSE:"close",ANS:"hidden",FFP:"rollOut",jnY:"rollOver",UEV:"shown"};Yq4.prototype.uV=function(){var e=Xvn(this,function(K){return K.type==="openUrl"&&K.url!=null});
return e?e.url:null};
var wPK={g8G:"anchored",LN:"branding",CHANNEL:"channel",qJA:"cta",l3A:"highlightText",glt:"label",PLAYLIST:"playlist",POPUP:"popup",Lst:"speech",SUBSCRIBE:"subscribe",lNt:"title",VIDEO:"video",p6_:"website"},Vmi={LN:"branding",ils:"card",sjy:"drawer",yNG:"highlight",RMA:"marker",kiV:"promotion",TEXT:"text",hzA:"widget"};g.X(rl,g.B);g.M=rl.prototype;g.M.addCueRange=function(e,K,S,I,A){e=new g.gi(e,K,{id:S,namespace:"annotations_module"});I&&this.cY.set(e,I);A&&this.Js.set(e,A);this.context.V.va([e],1)};
g.M.l4=function(){this.context.L.subscribe("resize",this.pA,this)};
g.M.yH=function(){return this.element};
g.M.hT=function(e,K,S,I,A,k){if(this.p8)return!1;k&&(k.stopPropagation(),k.preventDefault());this.navigate(e,S,I,A);return!1};
g.M.show=function(){};
g.M.hide=function(){};
g.M.destroy=function(){g.AC(this.yH())};
g.M.pA=function(){};
g.M.navigate=function(e,K,S,I){var A=this,k=a0(e);if(k){var P=qqS(k,e.target),b=function(){e.S&&A.context.V.pauseVideo();var N=A.context.videoData.Xo||!1,h=g.o5(k||"");N&&h&&(h.v||h.list)?A.context.V.Ze(h.v,K,h.list,!1):g.Rj(k||"",P==="current"?"_top":void 0,K)};
P==="new"&&(b(),b=null);S9(this.context.logger,S,b,I);Jla(k)||(S=g.jB(),I=K.itct,S&&I&&g.bB(S,g.l8(I)))}};
g.M.Lr=function(){this.cY.clear();this.Js.clear();g.B.prototype.Lr.call(this)};
g.M.createElement=function(e){e=new g.C(e);g.c(this,e);return e.element};g.X(lfK,rl);g.M=lfK.prototype;g.M.fh=function(){this.rY&&R0(this,this.rY)};
g.M.isAvailable=function(){var e;if(e=!!this.cards.length)(e=this.V.getRootNode())?(e=g.Ry(e),e=173<e.width&&173<e.height):e=!1;return e};
g.M.pA=function(){var e=this.isAvailable();g.dm(this.yH(),e);g.np(this.context.V.getRootNode(),g.IE.IV_DRAWER_ENABLED,e);uV(this.V)};
g.M.destroy=function(){this.V.Ql(!1);try{this.V.getRootNode().removeChild(this.W)}catch(e){}g.b9(this.zA);g.UI(this.xA);this.Cr&&this.Cr.dispose();this.G&&this.G.dispose();rl.prototype.destroy.call(this)};
g.M.ji=function(){var e=this;this.context.S.listen(g.sH("iv-drawer-close-button",this.W),"click",this.gG,this);this.context.S.listen(this.L,"touchend",function(){e.VA.start()});
this.context.S.listen(this.L,"scroll",this.I3,this);this.context.L.subscribe("onHideControls",function(){e.eG=!0});
this.context.L.subscribe("onShowControls",function(){e.eG=!1});
this.context.L.subscribe("onVideoAreaChange",function(){e.eG=g.g1(e.V.getRootNode(),"ytp-autohide")});
this.zA.push(g.M1("iv-button-shown",this.Vat,this));this.zA.push(g.M1("iv-button-hidden",this.taS,this));UpS(this)};
g.M.findLastIndex=function(e){if(this.cards.length===0)return 0;var K=g.Ta(this.cards,function(S){return e.SF.startMs>S.SF.startMs||e.SF.startMs===S.SF.startMs&&e.SF.timestamp>=S.SF.timestamp?!0:!1});
return K===-1?0:K+1};
g.M.gG=function(){if(this.Y){S9(this.context.logger,W$(this).lB.close);var e=g.jB();e&&this.N&&g.bB(e,this.N);DP(this)}};
g.M.I3=function(){g.np(this.W,"iv-drawer-scrolled",this.L.scrollTop>0)};
g.M.Vat=function(){var e=g.jB(),K=W$(this);K=K?K.Lv:this.Lv;e&&K&&g.op(e,[K])};
g.M.taS=function(){var e=g.jB(),K=W$(this);K=K?K.Lv:this.Lv;e&&K&&g.Mo(e,[K])};
g.M.iW=function(){var e=W$(this);S9(this.context.logger,e.lB.oT);var K=g.jB();if(K&&e)if(this.V.D("web_infocards_teaser_show_logging_fix")){var S=[];e.v2&&S.push(e.v2);e.Lv&&S.push(e.Lv);S.length>0&&g.op(K,S)}else g.op(K,[e.v2,e.Lv])};
g.M.A6A=function(){var e=g.jB(),K=W$(this);e&&K&&g.Mo(e,[K.v2])};
g.M.It=function(e){var K=W$(this),S=g.jB();this.S?e?(e=this.context.logger,S9(e,K.lB.md),e.V.sendVideoStatsEngageEvent(4,void 0),S&&K.v2&&g.bB(S,K.v2)):(e=this.context.logger,S9(e,K.lB.md),e.V.sendVideoStatsEngageEvent(4,void 0),S&&K.Lv&&g.bB(S,K.Lv)):(e=this.context.logger,S9(e,K.lB.md),e.V.sendVideoStatsEngageEvent(4,void 0),S&&this.Lv&&g.bB(S,this.Lv))};g.X(e9,rl);e9.prototype.l4=function(){rl.prototype.l4.call(this);Z8K(this)};
e9.prototype.show=function(){rl.prototype.show.call(this);var e=g.jB(),K=this.annotation.data;e&&K&&(K=K.session_data)&&g.op(e,[g.l8(K.itct)])};
e9.prototype.hide=function(){rl.prototype.hide.call(this);var e=g.jB(),K=this.annotation.data;e&&K&&(K=K.session_data)&&g.Mo(e,[g.l8(K.itct)])};g.X(KU,e9);
KU.prototype.show=function(){if(!this.isActive){e9.prototype.show.call(this);if(!this.N){g.o3(this.yH(),"iv-branding");var e=this.annotation.data;this.L=this.createElement({K:"img",kA:["branding-img","iv-click-target"],B:{"aria-label":"Channel watermark",src:e.image_url,width:e.image_width,height:e.image_height}});g.dm(this.L,!1);var K=this.createElement({K:"button",kA:["branding-img-container","ytp-button"]});K.appendChild(this.L);this.yH().appendChild(K);var S=this.annotation.uV();S&&CC(this,K,
S,this.annotation.id,e.session_data);this.context.V.D("disable_branding_context")||sVS(this,e);this.N=!0}g.dm(this.yH(),!0);this.isActive=!0;if(this.L){try{rlK(this,this.L)}catch(I){}g.o3(this.context.V.getRootNode(),"ytp-branding-shown");this.context.V.getRootNode().style.setProperty("--branding-image-width",this.L.getAttribute("width")+"px")}}};
KU.prototype.hide=function(){this.isActive&&(e9.prototype.hide.call(this),g.dm(this.yH(),!1),this.isActive=!1,g.b1(this.context.V.getRootNode(),"ytp-branding-shown"))};
KU.prototype.destroy=function(){this.S&&(this.S.dispose(),this.S=null);g.b1(this.context.V.getRootNode(),"ytp-branding-shown");e9.prototype.destroy.call(this)};g.X(Rt6,e9);g.M=Rt6.prototype;g.M.show=function(){this.isActive||(e9.prototype.show.call(this),this.U||(ztu(this),this.U=!0),g.dm(this.yH(),!0),g.Hm(function(){g.b1(this.yH(),"iv-promo-inactive")},100,this),this.yH().removeAttribute("aria-hidden"),this.isActive=!0,Kvu(this),F3a(this),W3S(this,this.Z))};
g.M.hide=function(){this.isActive&&(g.o3(this.yH(),"iv-promo-inactive"),this.isActive=!1,this.yH().setAttribute("aria-hidden","true"))};
g.M.hT=function(e,K,S,I,A,k){return this.isCollapsed?!1:e9.prototype.hT.call(this,e,K,S,I,A,k)};
g.M.br_=function(e){this.j=!0;dp4(this,500,e)};
g.M.qVY=function(){this.j=!1;e5a(this)};
g.M.Lys=function(e){e.stopPropagation();this.hide()};
g.M.YVy=function(e){e.stopPropagation();Kvu(this);this.isCollapsed=!0;g.o3(this.yH(),"iv-promo-collapsed-no-delay");this.G.start()};
g.M.destroy=function(){this.G.dispose();e9.prototype.destroy.call(this)};g.X(IXK,g.NK);g.M=IXK.prototype;g.M.Ke=function(e,K){if(!YGK(this.player.J().playerStyle))return null;switch(e){case "loadCustomAnnotationsXml":return(e=g.CB(K))&&gPu(this,e),!0;case "removeCustomAnnotationById":return K&&this.S&&(pvi(this.S,K),uV(this.player)),!0}return null};
g.M.getOptions=function(){return YGK(this.player.J().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.M.GC=function(){var e=this.player.J(),K=g.y(this.player.getVideoData()),S=e.annotationsLoadPolicy||K.annotationsLoadPolicy;return g.Ie(K)||this.player.isMutedByEmbedsMutedAutoplay()?!1:S===1&&!K.HR||e.RS.get(K.videoId)||g.af(K)||g.HT(K)?!0:!1};
g.M.L1=function(){if(this.Y){var e=this.player.UV().getVideoContentRect(!0);g.Dy(this.Y.element,e.width,e.height);g.rm(this.Y.element,e.left,e.top)}if(this.S){var K=this.player.Oc();e=this.S;K=K.width;g.np(e.W,"iv-drawer-small",K<=426);g.np(e.W,"iv-drawer-big",K>=1280)}};
g.M.cz=function(e){k04(this,e.state);g.D(e.state,2)&&(this.Vk()&&this.Y1()&&this.player.getPresentingPlayerType()!==2&&this.yl(!1),this.Ql(!1))};
g.M.load=function(){function e(P){var b=K.loadNumber;K.G=null;K.loaded&&K.loadNumber===b&&K.player.getVideoData().videoId===I&&(P=g.X8(P)&&P.responseXML?P.responseXML:null)&&(gPu(K,P),g.o3(K.player.getRootNode(),"iv-module-loaded"))}
var K=this;g.NK.prototype.load.call(this);k04(this,this.player.getPlayerStateObject());this.loadNumber++;var S=g.y(this.player.getVideoData()),I=S.videoId;g.Ps()&&(e=oP4(this,e));var A={format:"XML",onFinish:e,onError:function(){K.G=null},
urlParams:{}};S.isPharma&&(A.urlParams.pharma="1");A.method="POST";A.withCredentials=!0;var k=this.player.J().RS.get(I);k&&Mma(A,k);k=k&&(k.p6||k.g$);if(!S.Y0||k)S.Js?ixe(this,S.Js,A):(this.N=function(){if(!K.j)K.onVideoDataChange(A);var P=g.y(K.player.getVideoData());(P==null?0:g.BT(P))&&!K.zA&&nPY(K,P)},this.player.addEventListener("videodatachange",this.N));
g.QA(this.player,this.Y.element,4);this.L1();(k=g.af(S))&&h54(this,k);(k=g.HT(S))&&k.featuredChannel&&Tja(this,k.featuredChannel,k.annotationId||"branding",S.videoId||null,S.eventId||null);this.k6=g.sH("ytp-cards-button",this.player.getRootNode());g.BT(S)&&nPY(this,S)};
g.M.onVideoDataChange=function(e){var K=g.y(this.player.getVideoData());K.Js&&ixe(this,K.Js,e)};
g.M.unload=function(){this.player.TE("annotations_module");for(var e=g.f(Object.keys(this.Z)),K=e.next();!K.done;K=e.next())this.Z[K.value].destroy();this.U=null;this.S&&(this.S.destroy(),this.S=null,uV(this.player));this.j=!1;this.G&&(this.G.abort(),this.G=null);this.zA=!1;this.Z={};this.L.hide();g.NK.prototype.unload.call(this);this.Y.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.M.UY=function(e){e===this.player.getVideoData().videoId&&(this.loaded?bxk(this):this.load())};
g.M.Vk=function(){var e;return((e=this.S)==null?void 0:e.isAvailable())||this.zA};
g.M.Y1=function(){return!!this.S&&this.S.Y};
g.M.yl=function(e,K,S){K=K===void 0?!1:K;this.Vk();this.S&&(e?S?sd(this.S,S,K):sd(this.S,"YOUTUBE_DRAWER_AUTO_OPEN",K):DP(this.S))};
g.M.Ql=function(e,K){this.player.publish(e?"cardsteasershow":"cardsteaserhide",K)};
g.M.Lr=function(){this.player.J().RS.unsubscribe("vast_info_card_add",this.UY,this);g.b1(this.player.getRootNode(),g.IE.IV_DRAWER_OPEN);for(var e=this.rY,K=g.r2,S=0,I=e.length;S<I;S++)K.yk(e[S]);this.rY.length=0;g.NK.prototype.Lr.call(this)};
g.M.createElement=function(e){e=new g.C(e);g.c(this,e);return e.element};g.bT("annotations_module",IXK);g.bT("creatorendscreen",FAD);})(_yt_player);
