(function(g){var window=this;'use strict';var QzK=function(e){e.publish("autonavvisibility")},ZFi=function(e,K){e.Xt("onAutonavCoundownStarted",K)},rS6=function(e){var K,S,I;
return e==null?void 0:(K=e.playerOverlays)==null?void 0:(S=K.playerOverlayRenderer)==null?void 0:(I=S.autoplay)==null?void 0:I.playerOverlayAutoplayRenderer},ej=function(e,K,S){g.np(e.element,"ytp-suggestion-set",!!K.videoId);
var I=K.playlistId;S=K.D5(S?S:"mqdefault.jpg");var A=null,k=null;K instanceof g.vY&&(K.lengthText?(A=K.lengthText||null,k=K.iC||null):K.lengthSeconds&&(A=g.tn(K.lengthSeconds),k=g.tn(K.lengthSeconds,!0)));var P=!!I;I=P&&g.lN(I).type==="RD";var b=K instanceof g.vY?K.isLivePlayback:null,N=K instanceof g.vY?K.isUpcoming:null,h=K.author,n=K.shortViewCount,V=K.publishedTimeText,w=[],T=[];h&&w.push(h);n&&(w.push(n),T.push(n));V&&T.push(V);S={title:K.title,author:h,author_and_views:w.join(" \u2022 "),aria_label:K.ariaLabel||
g.$7("Watch $TITLE",{TITLE:K.title}),duration:A,timestamp:k,url:K.iB(),is_live:b,is_upcoming:N,is_list:P,is_mix:I,background:S?"background-image: url("+S+")":"",views_and_publish_time:T.join(" \u2022 "),autoplayAlternativeHeader:K.Dl};K instanceof g.tI&&(S.playlist_length=K.playlistLength);e.update(S)},Kj=function(e){var K=e.J(),S=K.W;
g.C.call(this,{K:"a",C:"ytp-autonav-suggestion-card",B:{href:"{{url}}",target:S?K.U:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{K:"div",kA:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],B:{style:"{{background}}"},X:[{K:"div",B:{"aria-label":"{{timestamp}}"},kA:["ytp-autonav-timestamp"],YA:"{{duration}}"},{K:"div",kA:["ytp-autonav-live-stamp"],YA:"Live"},{K:"div",
kA:["ytp-autonav-upcoming-stamp"],YA:"Upcoming"},{K:"div",C:"ytp-autonav-list-overlay",X:[{K:"div",C:"ytp-autonav-mix-text",YA:"Mix"},{K:"div",C:"ytp-autonav-mix-icon"}]}]},{K:"div",kA:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],YA:"{{title}}"},{K:"div",kA:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],YA:"{{author}}"},{K:"div",kA:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],YA:"{{views_and_publish_time}}"}]});this.V=e;this.suggestion=
null;this.S=S;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},Sj=function(e,K){K=K===void 0?!1:K;
g.C.call(this,{K:"div",C:"ytp-autonav-endscreen-countdown-overlay"});var S=this;this.N=K;this.cancelCommand=this.Z=void 0;this.Y=0;this.container=new g.C({K:"div",C:"ytp-autonav-endscreen-countdown-container"});g.c(this,this.container);this.container.As(this.element);K=e.J();var I=K.W;this.V=e;this.suggestion=null;this.onVideoDataChange("newdata",g.y(this.V.getVideoData()));this.T(e,"videodatachange",this.onVideoDataChange);this.S=new g.C({K:"div",C:"ytp-autonav-endscreen-upnext-container",B:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{K:"div",C:"ytp-autonav-endscreen-upnext-header"},{K:"div",C:"ytp-autonav-endscreen-upnext-alternative-header",YA:"{{autoplayAlternativeHeader}}"},{K:"a",C:"ytp-autonav-endscreen-link-container",B:{href:"{{url}}",target:I?K.U:""},X:[{K:"div",C:"ytp-autonav-endscreen-upnext-thumbnail",B:{style:"{{background}}"},X:[{K:"div",B:{"aria-label":"{{timestamp}}"},kA:["ytp-autonav-timestamp"],
YA:"{{duration}}"},{K:"div",kA:["ytp-autonav-live-stamp"],YA:"Live"},{K:"div",kA:["ytp-autonav-upcoming-stamp"],YA:"Upcoming"}]},{K:"div",C:"ytp-autonav-endscreen-video-info",X:[{K:"div",C:"ytp-autonav-endscreen-premium-badge"},{K:"div",C:"ytp-autonav-endscreen-upnext-title",YA:"{{title}}"},{K:"div",C:"ytp-autonav-endscreen-upnext-author",YA:"{{author}}"},{K:"div",C:"ytp-autonav-view-and-date",YA:"{{views_and_publish_time}}"},{K:"div",C:"ytp-autonav-author-and-view",YA:"{{author_and_views}}"}]}]}]});
g.c(this,this.S);this.S.As(this.container.element);I||this.T(this.S.qP("ytp-autonav-endscreen-link-container"),"click",this.d5);this.V.createClientVe(this.container.element,this,115127);this.V.createClientVe(this.S.qP("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.C({K:"div",C:"ytp-autonav-overlay"});g.c(this,this.overlay);this.overlay.As(this.container.element);this.L=new g.C({K:"div",C:"ytp-autonav-endscreen-button-container"});g.c(this,this.L);this.L.As(this.container.element);
this.cancelButton=new g.C({K:"button",kA:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",K.D("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],B:{"aria-label":"Cancel autoplay"},YA:"Cancel"});g.c(this,this.cancelButton);this.cancelButton.As(this.L.element);this.cancelButton.listen("click",this.mL,this);this.V.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.C({K:"a",kA:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
K.D("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],B:{href:"{{url}}",role:"button","aria-label":"Play next video"},YA:"Play Now"});g.c(this,this.playButton);this.playButton.As(this.L.element);this.playButton.listen("click",this.d5,this);this.V.createServerVe(this.playButton.element,this.playButton,!0);(K=this.V.getVideoData())&&Csa(this,K);this.W=new g.Wg(function(){OFa(S)},500);
g.c(this,this.W);this.XD();this.T(e,"autonavvisibility",this.XD);this.V.D("web_autonav_color_transition")&&(this.T(e,"autonavchange",this.fN),this.T(e,"onAutonavCoundownStarted",this.vRV))},I_=function(e){var K=e.V.Oc(!0,e.V.isFullscreen());
g.np(e.container.element,"ytp-autonav-endscreen-small-mode",e.KX(K));g.np(e.container.element,"ytp-autonav-endscreen-is-premium",!!e.suggestion&&!!e.suggestion.yrt);g.np(e.V.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!e.V.n3());g.np(e.V.getRootNode(),"countdown-running",e.iK());g.np(e.container.element,"ytp-player-content",e.V.n3());g.Bn(e.overlay.element,{width:K.width+"px"});if(!e.iK()){e.V.n3()?szk(e,Math.round(DEu(e)/1E3)):szk(e);K=!!e.suggestion&&!!e.suggestion.Dl;var S=e.V.n3()||
!K;g.np(e.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!S&&K);g.np(e.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",S&&!K);e.L.S9(e.V.n3());g.np(e.element,"ytp-enable-w2w-color-transitions",R2D(e))}},OFa=function(e){var K=DEu(e),S=Math,I=S.min;
var A=e.Y?Date.now()-e.Y:0;S=I.call(S,A,K);szk(e,Math.ceil((K-S)/1E3));K-S<=500&&e.iK()?e.select(!0):e.iK()&&e.W.start()},DEu=function(e){if(e.V.isFullscreen()){var K;
e=(K=e.V.getVideoData())==null?void 0:K.Pw;return e===-1||e===void 0?8E3:e}return e.V.mq()>=0?e.V.mq():g.Tn(e.V.J().experiments,"autoplay_time")||1E4},Csa=function(e,K){K=K.getWatchNextResponse();
var S,I;K=(S=rS6(K))==null?void 0:(I=S.nextButton)==null?void 0:I.buttonRenderer;e.Z=K==null?void 0:K.navigationEndpoint;S=K==null?void 0:K.trackingParams;e.playButton&&S&&e.V.setTrackingParams(e.playButton.element,S)},R2D=function(e){var K;
return!((K=e.V.getVideoData())==null||!K.watchToWatchTransitionRenderer)},szk=function(e,K){K=K===void 0?-1:K;
e=e.S.qP("ytp-autonav-endscreen-upnext-header");g.S2(e);if(K>=0){K=String(K);var S="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],I="Up next in $SECONDS".indexOf(S);if(I>=0){e.appendChild(g.e2("Up next in $SECONDS".slice(0,I)));var A=g.W3("span");g.Pq(A,"ytp-autonav-endscreen-upnext-header-countdown-number");g.iD(A,K);e.appendChild(A);e.appendChild(g.e2("Up next in $SECONDS".slice(I+S.length)));return}}g.iD(e,"Up next")},AQ=function(e,K){g.C.call(this,{K:"div",
kA:["html5-endscreen","ytp-player-content",K||"base-endscreen"]});this.created=!1;this.player=e},kF=function(e){g.C.call(this,{K:"div",
kA:["ytp-upnext","ytp-player-content"],B:{"aria-label":"{{aria_label}}"},X:[{K:"div",C:"ytp-cued-thumbnail-overlay-image",B:{style:"{{background}}"}},{K:"span",C:"ytp-upnext-top",X:[{K:"span",C:"ytp-upnext-header",YA:"Up Next"},{K:"span",C:"ytp-upnext-title",YA:"{{title}}"},{K:"span",C:"ytp-upnext-author",YA:"{{author}}"}]},{K:"a",C:"ytp-upnext-autoplay-icon",B:{role:"button",href:"{{url}}","aria-label":"Play next video"},X:[{K:"svg",B:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
X:[{K:"circle",C:"ytp-svg-autoplay-circle",B:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{K:"circle",C:"ytp-svg-autoplay-ring",B:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{K:"path",C:"ytp-svg-fill",B:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{K:"span",C:"ytp-upnext-bottom",X:[{K:"span",C:"ytp-upnext-cancel"},{K:"span",C:"ytp-upnext-paused",
YA:"Autoplay is paused"}]}]});this.api=e;this.cancelButton=null;this.Z=this.qP("ytp-svg-autoplay-ring");this.Y=this.notification=this.S=this.suggestion=null;this.W=new g.Wg(this.W5,5E3,this);this.L=0;var K=this.qP("ytp-upnext-cancel");this.cancelButton=new g.C({K:"button",kA:["ytp-upnext-cancel-button","ytp-button"],B:{tabindex:"0","aria-label":"Cancel autoplay"},YA:"Cancel"});g.c(this,this.cancelButton);this.cancelButton.listen("click",this.J7,this);this.cancelButton.As(K);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.c(this,this.W);this.api.createClientVe(this.element,this,18788);K=this.qP("ytp-upnext-autoplay-icon");this.T(K,"click",this.Hz);this.api.createClientVe(K,this,115130);this.w5();this.T(e,"autonavvisibility",this.w5);this.T(e,"mdxnowautoplaying",this.fsV);this.T(e,"mdxautoplaycanceled",this.mLA);g.np(this.element,"ytp-upnext-mobile",this.api.J().L)},dEK=function(e,K){if(K)return K;
if(e.api.isFullscreen()){var S;e=(S=e.api.getVideoData())==null?void 0:S.Pw;return e===-1||e===void 0?8E3:e}return e.api.mq()>=0?e.api.mq():g.Tn(e.api.J().experiments,"autoplay_time")||1E4},z2n=function(e,K){K=dEK(e,K);
var S=Math,I=S.min;var A=(0,g.r)()-e.L;S=I.call(S,A,K);K=K===0?1:Math.min(S/K,1);e.Z.setAttribute("stroke-dashoffset",""+-211*(K+1));K>=1&&e.iK()&&e.api.getPresentingPlayerType()!==3?e.select(!0):e.iK()&&e.S.start()},P1=function(e){AQ.call(this,e,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.C({K:"div",C:"ytp-suggestion-panel",X:[{K:"div",kA:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],YA:"More videos"}]});this.j=new g.C({K:"div",C:"ytp-suggestions-container"});this.videos=[];this.Y=null;this.Z=this.N=!1;this.L=new Sj(this.player);g.c(this,this.L);this.L.As(this.element);e.getVideoData().yq?this.S=this.L:(this.S=new kF(e),g.QA(this.player,this.S.element,4),g.c(this,this.S));this.overlay=new g.C({K:"div",
C:"ytp-autonav-overlay-cancelled-state"});g.c(this,this.overlay);this.overlay.As(this.element);this.W=new g.Qv(this);g.c(this,this.W);g.c(this,this.table);this.table.As(this.element);this.table.show();g.c(this,this.j);this.j.As(this.table.element);this.hide()},gQ=function(e){var K=e.n3();
K!==e.Z&&(e.Z=K,QzK(e.player),e.Z?(e.L!==e.S&&e.L.hide(),e.table.hide()):(e.L!==e.S&&e.L.show(),e.table.show()))},o_=function(e,K){g.C.call(this,{K:"button",
kA:["ytp-watch-on-youtube-button","ytp-button"],YA:"{{content}}"});this.V=e;this.buttonType=this.buttonType=K;this.DP();this.buttonType===2&&g.o3(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.DP);this.S9(!0)},MT=function(e,K){AQ.call(this,e,"embeds-lite-endscreen");
this.V=e;this.S=K;this.V.createClientVe(this.element,this,156943);this.watchButton=new o_(e,2);g.c(this,this.watchButton);this.watchButton.As(this.element);this.hide()},bn=function(e){var K=e.J(),S=g.Bw||g.py?{style:"will-change: opacity"}:void 0,I=K.W,A=["ytp-modern-videowall-still"];
K.L&&A.push("ytp-videowall-show-text");g.C.call(this,{K:"a",kA:A,B:{href:"{{url}}",target:I?K.U:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},X:[{K:"div",C:"ytp-modern-videowall-still-image",B:{style:"{{background}}"},X:[{K:"span",C:"ytp-modern-videowall-still-info-duration",YA:"{{duration}}"}]},{K:"span",C:"ytp-modern-videowall-still-info",B:{"aria-hidden":"true"},X:[{K:"span",C:"ytp-modern-videowall-still-info-bg",X:[{K:"span",
C:"ytp-modern-videowall-still-info-content",B:S,X:[{K:"span",C:"ytp-modern-videowall-still-info-title",YA:"{{title}}"},{K:"span",C:"ytp-modern-videowall-still-info-author",YA:"{{author_and_views}}"},{K:"span",C:"ytp-modern-videowall-still-info-live",YA:"Live"}]}]}]},{K:"span",kA:["ytp-modern-videowall-still-listlabel-regular","ytp-modern-videowall-still-listlabel"],B:{"aria-hidden":"true"},X:[{K:"span",C:"ytp-modern-videowall-still-listlabel-icon"},"Playlist",{K:"span",C:"ytp-modern-videowall-still-listlabel-length",
X:[" (",{K:"span",YA:"{{playlist_length}}"},")"]}]},{K:"span",kA:["ytp-modern-videowall-still-listlabel-mix","ytp-modern-videowall-still-listlabel"],B:{"aria-hidden":"true"},X:[{K:"span",C:"ytp-modern-videowall-still-listlabel-mix-icon"},"Mix",{K:"span",C:"ytp-modern-videowall-still-listlabel-length",YA:" (50+)"}]}]});this.suggestion=null;this.L=I;this.api=e;this.S=new g.Qv(this);g.c(this,this.S);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.S.T(e,"videodatachange",
this.onVideoDataChange);e.createServerVe(this.element,this);this.onVideoDataChange()},Fs6=function(e){AQ.call(this,e,"videowall-endscreen");
var K=this;this.V=e;this.stills=[];this.Y=this.videoData=null;this.W=this.N=!1;this.j=null;g.o3(this.element,"modern-videowall-endscreen");this.L=new g.Qv(this);g.c(this,this.L);this.Z=new g.Wg(function(){g.o3(K.element,"ytp-show-tiles")},0);
g.c(this,this.Z);this.table=new g.wv({K:"div",C:"ytp-modern-endscreen-content"});g.c(this,this.table);this.table.As(this.element);e.getVideoData().yq?this.S=new Sj(e,!0):this.S=new kF(e);g.c(this,this.S);g.QA(this.player,this.S.element,4);e.createClientVe(this.element,this,158789);this.hide()},NT=function(e){return g.ZH(e.player)&&e.Nv()&&!e.Y},hQ=function(e){var K=e.n3();
K!==e.N&&(e.N=K,QzK(e.player))},Wsk=function(e){AQ.call(this,e,"subscribecard-endscreen");
this.S=new g.C({K:"div",C:"ytp-subscribe-card",X:[{K:"img",C:"ytp-author-image",B:{src:"{{profilePicture}}"}},{K:"div",C:"ytp-subscribe-card-right",X:[{K:"div",C:"ytp-author-name",YA:"{{author}}"},{K:"div",C:"html5-subscribe-button-container"}]}]});g.c(this,this.S);this.S.As(this.element);var K=e.getVideoData();this.subscribeButton=new g.OZ("Subscribe",null,"Unsubscribe",null,!0,!1,K.bf,K.subscribed,"trailer-endscreen",null,e,!1);g.c(this,this.subscribeButton);this.subscribeButton.As(this.S.qP("html5-subscribe-button-container"));
this.T(e,"videodatachange",this.IS);this.IS();this.hide()},nj=function(e){var K=e.J(),S=g.Bw||g.py?{style:"will-change: opacity"}:void 0,I=K.W,A=["ytp-videowall-still"];
K.L&&A.push("ytp-videowall-show-text");g.C.call(this,{K:"a",kA:A,B:{href:"{{url}}",target:I?K.U:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},X:[{K:"div",C:"ytp-videowall-still-image",B:{style:"{{background}}"}},{K:"span",C:"ytp-videowall-still-info",B:{"aria-hidden":"true"},X:[{K:"span",C:"ytp-videowall-still-info-bg",X:[{K:"span",C:"ytp-videowall-still-info-content",B:S,X:[{K:"span",C:"ytp-videowall-still-info-title",YA:"{{title}}"},
{K:"span",C:"ytp-videowall-still-info-author",YA:"{{author_and_views}}"},{K:"span",C:"ytp-videowall-still-info-live",YA:"Live"},{K:"span",C:"ytp-videowall-still-info-duration",YA:"{{duration}}"}]}]}]},{K:"span",kA:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],B:{"aria-hidden":"true"},X:[{K:"span",C:"ytp-videowall-still-listlabel-icon"},"Playlist",{K:"span",C:"ytp-videowall-still-listlabel-length",X:[" (",{K:"span",YA:"{{playlist_length}}"},")"]}]},{K:"span",kA:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],B:{"aria-hidden":"true"},X:[{K:"span",C:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{K:"span",C:"ytp-videowall-still-listlabel-length",YA:" (50+)"}]}]});this.suggestion=null;this.L=I;this.api=e;this.S=new g.Qv(this);g.c(this,this.S);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.S.T(e,"videodatachange",this.onVideoDataChange);e.createServerVe(this.element,this);this.onVideoDataChange()},Vz=function(e){AQ.call(this,e,"videowall-endscreen");
var K=this;this.V=e;this.Y=0;this.stills=[];this.W=this.videoData=null;this.Z=this.j=!1;this.U=null;this.L=new g.Qv(this);g.c(this,this.L);this.N=new g.Wg(function(){g.o3(K.element,"ytp-show-tiles")},0);
g.c(this,this.N);var S=new g.C({K:"button",kA:["ytp-button","ytp-endscreen-previous"],B:{"aria-label":"Previous"},X:[g.J7()]});g.c(this,S);S.As(this.element);S.listen("click",this.Py,this);this.table=new g.wv({K:"div",C:"ytp-endscreen-content"});g.c(this,this.table);this.table.As(this.element);S=new g.C({K:"button",kA:["ytp-button","ytp-endscreen-next"],B:{"aria-label":"Next"},X:[g.qo()]});g.c(this,S);S.As(this.element);S.listen("click",this.U8,this);e.getVideoData().yq?this.S=new Sj(e,!0):this.S=
new kF(e);g.c(this,this.S);g.QA(this.player,this.S.element,4);e.createClientVe(this.element,this,158789);this.hide()},wQ=function(e){return g.ZH(e.player)&&e.Nv()&&!e.W},Tz=function(e){var K=e.n3();
K!==e.j&&(e.j=K,QzK(e.player))},YF=function(e){AQ.call(this,e,"watch-again-on-youtube-endscreen");
this.watchButton=new o_(e,1);g.c(this,this.watchButton);this.watchButton.As(this.element);g.ds4(e)&&(this.S=new g.s3(e),g.c(this,this.S),this.L=new g.C({K:"div",kA:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],B:{tabIndex:"-1"},X:[this.S]}),g.c(this,this.L),this.S.As(this.L.element),this.L.As(this.element));e.createClientVe(this.element,this,156914);this.hide()},Iv6=function(e){g.NK.call(this,e);
var K=this;this.endScreen=null;this.L=this.S=this.Y=this.W=!1;this.listeners=new g.Qv(this);g.c(this,this.listeners);var S=e.J(),I=e.getVideoData();I=I&&I.limitedPlaybackDurationInSeconds!==0;g.Vj(g.rX(S))&&I&&!g.Bh(e)?(this.L=!0,this.endScreen=new MT(e,g.mc(e))):e.isEmbedsShortsMode()?this.endScreen=new YF(e):eZi(e)?(this.W=!0,KDK(this),this.S?this.endScreen=new P1(e):S.D("delhi_modern_endscreen")?this.endScreen=new Fs6(e):this.endScreen=new Vz(e)):S.TX?this.endScreen=new Wsk(e):this.endScreen=new AQ(e);
g.c(this,this.endScreen);g.QA(e,this.endScreen.element,4);SNu(this);this.listeners.T(e,"videodatachange",this.onVideoDataChange,this);this.listeners.T(e,g.Mc("endscreen"),function(A){K.onCueRangeEnter(A)});
this.listeners.T(e,g.bk("endscreen"),function(A){K.onCueRangeExit(A)})},KDK=function(e){var K=e.player.getVideoData();
if(!K||e.S===K.eP&&e.Y===K.yq)return!1;e.S=K.eP;e.Y=K.yq;return!0},eZi=function(e){e=e.J();
return e.oR&&!e.TX&&!e.disableOrganicUi},SNu=function(e){e.player.TE("endscreen");
var K=e.player.getVideoData();K=new g.gi(Math.max((K.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var S=new g.gi(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});e.player.va([K,S])};
g.xY.prototype.mq=g.il(14,function(){return this.app.mq()});
g.hJ.prototype.mq=g.il(13,function(){return this.getVideoData().uL});
g.tv.prototype.SB=g.il(12,function(e){this.mG().SB(e)});
g.i4.prototype.SB=g.il(11,function(e){this.S!==e&&(this.S=e,this.IS())});
g.LE.prototype.SB=g.il(10,function(e){this.overflowButton&&this.overflowButton.SB(e)});
g.tv.prototype.vJ=g.il(9,function(e){this.mG().vJ(e)});
g.NR.prototype.vJ=g.il(8,function(e){this.L!==e&&(this.L=e,this.IS())});
g.LE.prototype.vJ=g.il(7,function(e){this.shareButton&&this.shareButton.vJ(e)});
g.tv.prototype.R9=g.il(6,function(e){this.mG().R9(e)});
g.at.prototype.R9=g.il(5,function(e){this.l7!==e&&(this.l7=e,this.sR())});
g.tv.prototype.Ga=g.il(4,function(e){this.mG().Ga(e)});
g.LE.prototype.Ga=g.il(3,function(e){this.yG!==e&&(this.yG=e,this.GQ())});g.X(Kj,g.C);Kj.prototype.select=function(){this.V.Ze(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.L5||void 0)&&this.V.logClick(this.element)};
Kj.prototype.onClick=function(e){g.hw(e,this.V,this.S,this.suggestion.sessionData||void 0)&&this.select()};
Kj.prototype.onKeyPress=function(e){switch(e.keyCode){case 13:case 32:e.defaultPrevented||(this.select(),e.preventDefault())}};g.X(Sj,g.C);g.M=Sj.prototype;g.M.QC=function(e){this.suggestion!==e&&(this.suggestion=e,ej(this.S,e),this.playButton.updateValue("url",this.suggestion.iB()),I_(this))};
g.M.iK=function(){return this.Y>0};
g.M.Cq=function(){this.iK()||(this.Y=Date.now(),OFa(this),ZFi(this.V,DEu(this)),g.np(this.V.getRootNode(),"countdown-running",this.iK()))};
g.M.Uv=function(){this.Fe();OFa(this);var e=this.S.qP("ytp-autonav-endscreen-upnext-header");e&&g.iD(e,"Up next")};
g.M.Fe=function(){this.iK()&&(this.W.stop(),this.Y=0)};
g.M.select=function(e){this.V.nextVideo(!1,e===void 0?!1:e);this.Fe()};
g.M.d5=function(e){g.hw(e,this.V)&&(e.currentTarget===this.playButton.element?this.V.logClick(this.playButton.element):e.currentTarget===this.S.qP("ytp-autonav-endscreen-link-container")&&(e=this.S.qP("ytp-autonav-endscreen-link-container"),this.V.logVisibility(e,!0),this.V.logClick(e)),this.Z?(this.V.Xt("innertubeCommand",this.Z),this.Fe()):this.select())};
g.M.mL=function(){this.V.logClick(this.cancelButton.element);g.UX(this.V,!0);this.cancelCommand&&this.V.Xt("innertubeCommand",this.cancelCommand)};
g.M.onVideoDataChange=function(e,K){Csa(this,K);e=K.getWatchNextResponse();var S,I;e=(S=rS6(e))==null?void 0:(I=S.cancelButton)==null?void 0:I.buttonRenderer;this.cancelCommand=e==null?void 0:e.command};
g.M.vRV=function(e){if(R2D(this)){var K=this.V.getVideoData().watchToWatchTransitionRenderer,S=K==null?void 0:K.fromColorPaletteDark;K=K==null?void 0:K.toColorPaletteDark;if(S&&K){var I=this.element;I.style.setProperty("--w2w-start-background-color",g.CP(S.surgeColor));I.style.setProperty("--w2w-start-primary-text-color",g.CP(S.primaryTitleColor));I.style.setProperty("--w2w-start-secondary-text-color",g.CP(S.secondaryTitleColor));I.style.setProperty("--w2w-end-background-color",g.CP(K.surgeColor));
I.style.setProperty("--w2w-end-primary-text-color",g.CP(K.primaryTitleColor));I.style.setProperty("--w2w-end-secondary-text-color",g.CP(K.secondaryTitleColor));I.style.setProperty("--w2w-animation-duration",e+"ms")}g.np(this.element,"ytp-w2w-animate",!0)}};
g.M.fN=function(e){this.V.D("web_autonav_color_transition")&&e!==2&&g.np(this.element,"ytp-w2w-animate",!1)};
g.M.XD=function(){var e=this.V.n3();this.N&&this.rN!==e&&this.S9(e);I_(this);this.V.logVisibility(this.container.element,e);this.V.logVisibility(this.cancelButton.element,e);this.V.logVisibility(this.S.qP("ytp-autonav-endscreen-link-container"),e);this.V.logVisibility(this.playButton.element,e)};
g.M.KX=function(e){return e.width<400||e.height<459};g.X(AQ,g.C);g.M=AQ.prototype;g.M.create=function(){this.created=!0};
g.M.destroy=function(){this.created=!1};
g.M.Nv=function(){return!1};
g.M.n3=function(){return!1};
g.M.Oq=function(){return!1};g.X(kF,g.C);g.M=kF.prototype;g.M.W5=function(){this.notification&&(this.W.stop(),this.yx(this.Y),this.Y=null,this.notification.close(),this.notification=null)};
g.M.QC=function(e){this.suggestion=e;ej(this,e,"hqdefault.jpg")};
g.M.w5=function(){this.S9(this.api.n3());this.api.logVisibility(this.element,this.api.n3());this.api.logVisibility(this.qP("ytp-upnext-autoplay-icon"),this.api.n3());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.n3())};
g.M.Bor=function(){window.focus();this.W5()};
g.M.Cq=function(e){var K=this;this.iK()||(g.N1("a11y-announce","Up Next "+this.suggestion.title),this.L=(0,g.r)(),this.S=new g.Wg(function(){z2n(K,e)},25),z2n(this,e),ZFi(this.api,dEK(this,e)));
g.b1(this.element,"ytp-upnext-autoplay-paused")};
g.M.hide=function(){g.C.prototype.hide.call(this)};
g.M.iK=function(){return!!this.S};
g.M.Uv=function(){this.Fe();this.L=(0,g.r)();z2n(this);g.o3(this.element,"ytp-upnext-autoplay-paused")};
g.M.Fe=function(){this.iK()&&(this.S.dispose(),this.S=null)};
g.M.select=function(e){e=e===void 0?!1:e;if(this.api.J().D("autonav_notifications")&&e&&window.Notification&&typeof document.hasFocus==="function"){var K=Notification.permission;K==="default"?Notification.requestPermission():K!=="granted"||document.hasFocus()||(this.W5(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.D5()}),this.Y=this.T(this.notification,"click",this.Bor),this.W.start())}this.Fe();this.api.nextVideo(!1,e)};
g.M.Hz=function(e){!g.ka(this.cancelButton.element,e.target)&&g.hw(e,this.api)&&(this.api.n3()&&this.api.logClick(this.qP("ytp-upnext-autoplay-icon")),this.select())};
g.M.J7=function(){this.api.n3()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.UX(this.api,!0)};
g.M.fsV=function(e){this.api.getPresentingPlayerType();this.show();this.Cq(e)};
g.M.mLA=function(){this.api.getPresentingPlayerType();this.Fe();this.hide()};
g.M.Lr=function(){this.Fe();this.W5();g.C.prototype.Lr.call(this)};g.X(P1,AQ);g.M=P1.prototype;g.M.create=function(){AQ.prototype.create.call(this);this.W.T(this.player,"appresize",this.AF);this.W.T(this.player,"onVideoAreaChange",this.AF);this.W.T(this.player,"videodatachange",this.onVideoDataChange);this.W.T(this.player,"autonavchange",this.Bx);this.W.T(this.player,"onAutonavCancelled",this.X_);this.onVideoDataChange()};
g.M.show=function(){AQ.prototype.show.call(this);(this.N||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.UX(this.player,!1);g.ZH(this.player)&&this.Nv()&&!this.Y?(gQ(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.S.select(!0):this.S.Cq():this.videoData.autonavState===3&&this.S.Uv()):(g.UX(this.player,!0),gQ(this));this.AF()};
g.M.hide=function(){AQ.prototype.hide.call(this);this.S.Uv();gQ(this)};
g.M.AF=function(){var e=this.player.Oc(!0,this.player.isFullscreen());gQ(this);I_(this.L);g.np(this.element,"ytp-autonav-cancelled-small-mode",this.KX(e));g.np(this.element,"ytp-autonav-cancelled-tiny-mode",this.Om(e));g.np(this.element,"ytp-autonav-cancelled-mini-mode",e.width<=400||e.height<=360);this.overlay&&g.Bn(this.overlay.element,{width:e.width+"px"});if(!this.Z)for(e=0;e<this.videos.length;e++)g.np(this.videos[e].element,"ytp-suggestion-card-with-margin",e%2===1)};
g.M.onVideoDataChange=function(){var e=this.player.getVideoData();if(this.videoData!==e&&e){this.videoData=e;if((e=this.videoData.suggestions)&&e.length||this.player.D("web_player_autonav_empty_suggestions_fix")){var K=g.km(this.videoData);K&&(this.S.QC(K),this.S!==this.L&&this.L.QC(K))}if(e&&e.length)for(K=0;K<A34.length;++K){var S=A34[K];if(e&&e[S]){this.videos[K]=new Kj(this.player);var I=this.videos[K];S=e[S];I.suggestion!==S&&(I.suggestion=S,ej(I,S));g.c(this,this.videos[K]);this.videos[K].As(this.j.element)}}this.AF()}};
g.M.Bx=function(e){e===1?(this.N=!1,this.Y=this.videoData.clientPlaybackNonce,this.S.Fe(),this.rN&&this.AF()):(this.N=!0,this.n3()&&(e===2?this.S.Cq():e===3&&this.S.Uv()))};
g.M.X_=function(e){e?this.Bx(1):(this.Y=null,this.N=!1)};
g.M.Nv=function(){return this.videoData.autonavState!==1};
g.M.KX=function(e){return(e.width<910||e.height<459)&&!this.Om(e)&&!(e.width<=400||e.height<=360)};
g.M.Om=function(e){return e.width<800&&!(e.width<=400||e.height<=360)};
g.M.n3=function(){return this.rN&&g.ZH(this.player)&&this.Nv()&&!this.Y};
var A34=[1,3,2,4];g.X(o_,g.C);g.M=o_.prototype;g.M.DP=function(){switch(this.buttonType){case 1:var e="Watch again on YouTube";var K=156915;break;case 2:e="Continue watching on YouTube";K=156942;break;default:e="Continue watching on YouTube",K=156942}this.update({content:e});this.V.hasVe(this.element)&&this.V.destroyVe(this.element);this.V.createClientVe(this.element,this,K)};
g.M.onClick=function(e){this.V.D("web_player_log_click_before_generating_ve_conversion_params")&&this.V.logClick(this.element);g.nT(this.getVideoUrl(),this.V,e);this.V.D("web_player_log_click_before_generating_ve_conversion_params")||this.V.logClick(this.element)};
g.M.getVideoUrl=function(){var e=!0;switch(this.buttonType){case 1:e=!0;break;case 2:e=!1}e=this.V.getVideoUrl(e,!1,!1,!0);var K=this.V.J();if(g.Gy(K)){var S={};g.Gy(K)&&g.YY(this.V,"addEmbedsConversionTrackingParams",[S]);e=g.xa(e,S)}return e};
g.M.logVisibility=function(){this.V.logVisibility(this.element,this.rN&&this.G)};
g.M.show=function(){g.C.prototype.show.call(this);this.logVisibility()};
g.M.hide=function(){g.C.prototype.hide.call(this);this.logVisibility()};
g.M.i6=function(e){g.C.prototype.i6.call(this,e);this.logVisibility()};g.X(MT,AQ);MT.prototype.show=function(){this.player.getPlayerState()!==3&&(AQ.prototype.show.call(this),this.S.Ga(!0),this.S.vJ(!0),this.V.J().xI||this.S.SB(!0),this.V.logVisibility(this.element,!0),this.watchButton.i6(!0))};
MT.prototype.hide=function(){AQ.prototype.hide.call(this);this.S.Ga(!1);this.S.vJ(!1);this.S.SB(!1);this.V.logVisibility(this.element,!1);this.watchButton.i6(!1)};g.X(bn,g.C);bn.prototype.select=function(){this.api.Ze(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.L5||void 0)&&this.api.logClick(this.element)};
bn.prototype.onClick=function(e){if(g.Gy(this.api.J())&&this.api.D("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var K=this.suggestion.iB(),S={};g.ae(this.api,S);K=g.xa(K,S);g.nT(K,this.api,e)}else g.hw(e,this.api,this.L,this.suggestion.sessionData||void 0)&&this.select()};
bn.prototype.onKeyPress=function(e){switch(e.keyCode){case 13:case 32:e.defaultPrevented||(this.select(),e.preventDefault())}};
bn.prototype.onVideoDataChange=function(){var e=this.api.getVideoData(),K=this.api.J();this.L=e.Xo?!1:K.W};g.X(Fs6,AQ);g.M=Fs6.prototype;g.M.create=function(){AQ.prototype.create.call(this);var e=this.player.getVideoData();e&&(this.videoData=e);this.Bk();this.L.T(this.player,"appresize",this.Bk);this.L.T(this.player,"onVideoAreaChange",this.Bk);this.L.T(this.player,"videodatachange",this.onVideoDataChange);this.L.T(this.player,"autonavchange",this.Tt);this.L.T(this.player,"onAutonavCancelled",this.dF);e=this.videoData.autonavState;e!==this.j&&this.Tt(e);this.L.T(this.element,"transitionend",this.wF)};
g.M.destroy=function(){g.UI(this.L);g.hS(this.stills);this.stills=[];AQ.prototype.destroy.call(this);g.b1(this.element,"ytp-show-tiles");this.Z.stop();this.j=this.videoData.autonavState};
g.M.Nv=function(){return this.videoData.autonavState!==1};
g.M.show=function(){var e=this.rN;AQ.prototype.show.call(this);g.b1(this.element,"ytp-show-tiles");this.player.J().L?g.Kp(this.Z):this.Z.start();(this.W||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.UX(this.player,!1);NT(this)?(hQ(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.S.select(!0):this.S.Cq():this.videoData.autonavState===3&&this.S.Uv()):(g.UX(this.player,!0),hQ(this));e!==this.rN&&this.player.logVisibility(this.element,!0)};
g.M.hide=function(){var e=this.rN;AQ.prototype.hide.call(this);this.S.Uv();hQ(this);e!==this.rN&&this.player.logVisibility(this.element,!1)};
g.M.wF=function(e){e.target===this.element&&this.Bk()};
g.M.Bk=function(){var e,K,S,I;var A=((e=this.videoData)==null?0:(K=e.suggestions)==null?0:K.length)?(S=this.videoData)==null?void 0:S.suggestions:[(I=this.videoData)==null?void 0:g.km(I)];if(A.length){K=this.V.Oc(!0,this.V.isFullscreen());e=Math.floor((K.width-64+16)/(g.lp(K.width*.27,250,450)+16));K=Math.min(3,Math.floor((K.height-64)/((K.width-64-(e-1)*16)/e*.5625+70)));g.Nr(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.o3(this.element,"ytp-modern-endscreen-limit-rows-"+K);g.np(this.element,"ytp-modern-endscreen-single-item",e===1);g.np(this.element,"ytp-modern-endscreen-row-0",K===0);e=this.table.element;e.ariaLive="polite";this.S.QC(g.km(this.videoData));this.S instanceof Sj&&I_(this.S);g.np(this.element,"ytp-endscreen-takeover",NT(this));hQ(this);K=0;e.ariaBusy="true";S=A.length;for(I=0;I<S;I++){var k=I%S,P=this.stills[I];P||(P=new bn(this.player),this.stills[I]=P,e.appendChild(P.element));k=A[k];if(P.suggestion!==
k){P.suggestion=k;var b=P.api.J();ej(P,k,"hqdefault.jpg");if(g.Gy(b)&&!P.api.D("web_player_log_click_before_generating_ve_conversion_params")){b=k.iB();var N={};g.YY(P.api,"addEmbedsConversionTrackingParams",[N]);b=g.xa(b,N);P.updateValue("url",b)}(k=(k=k.sessionData)&&k.itct)&&P.api.setTrackingParams(P.element,k)}K++}this.stills.length=K}};
g.M.onVideoDataChange=function(){var e=this.player.getVideoData(1);this.videoData!==e&&(e!=null&&g.km(e)?(this.videoData=e,this.Bk()):this.player.vY("missg",{vid:(e==null?void 0:e.videoId)||"",cpn:(e==null?void 0:e.clientPlaybackNonce)||""}))};
g.M.Oq=function(){return this.S.iK()};
g.M.Tt=function(e){e===1?(this.W=!1,this.Y=this.videoData.clientPlaybackNonce,this.S.Fe(),this.rN&&this.Bk()):(this.W=!0,this.rN&&NT(this)&&(e===2?this.S.Cq():e===3&&this.S.Uv()))};
g.M.dF=function(e){if(e){for(e=0;e<this.stills.length;e++)this.V.logVisibility(this.stills[e].element,!0);this.Tt(1)}else this.Y=null,this.W=!1;this.Bk()};
g.M.n3=function(){return this.rN&&NT(this)};g.X(Wsk,AQ);Wsk.prototype.IS=function(){var e=this.player.getVideoData();this.S.update({profilePicture:e.profilePicture,author:e.author});this.subscribeButton.channelId=e.bf;var K=this.subscribeButton;e.subscribed?K.S():K.L()};g.X(nj,g.C);nj.prototype.select=function(){this.api.Ze(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.L5||void 0)&&this.api.logClick(this.element)};
nj.prototype.onClick=function(e){if(g.Gy(this.api.J())&&this.api.D("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var K=this.suggestion.iB(),S={};g.ae(this.api,S);K=g.xa(K,S);g.nT(K,this.api,e)}else g.hw(e,this.api,this.L,this.suggestion.sessionData||void 0)&&this.select()};
nj.prototype.onKeyPress=function(e){switch(e.keyCode){case 13:case 32:e.defaultPrevented||(this.select(),e.preventDefault())}};
nj.prototype.onVideoDataChange=function(){var e=this.api.getVideoData(),K=this.api.J();this.L=e.Xo?!1:K.W};g.X(Vz,AQ);g.M=Vz.prototype;g.M.create=function(){AQ.prototype.create.call(this);var e=this.player.getVideoData();e&&(this.videoData=e);this.ER();this.L.T(this.player,"appresize",this.ER);this.L.T(this.player,"onVideoAreaChange",this.ER);this.L.T(this.player,"videodatachange",this.onVideoDataChange);this.L.T(this.player,"autonavchange",this.Fz);this.L.T(this.player,"onAutonavCancelled",this.Bz);e=this.videoData.autonavState;e!==this.U&&this.Fz(e);this.L.T(this.element,"transitionend",this.pS)};
g.M.destroy=function(){g.UI(this.L);g.hS(this.stills);this.stills=[];AQ.prototype.destroy.call(this);g.b1(this.element,"ytp-show-tiles");this.N.stop();this.U=this.videoData.autonavState};
g.M.Nv=function(){return this.videoData.autonavState!==1};
g.M.show=function(){var e=this.rN;AQ.prototype.show.call(this);g.b1(this.element,"ytp-show-tiles");this.player.J().L?g.Kp(this.N):this.N.start();(this.Z||this.W&&this.W!==this.videoData.clientPlaybackNonce)&&g.UX(this.player,!1);wQ(this)?(Tz(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.S.select(!0):this.S.Cq():this.videoData.autonavState===3&&this.S.Uv()):(g.UX(this.player,!0),Tz(this));e!==this.rN&&this.player.logVisibility(this.element,!0)};
g.M.hide=function(){var e=this.rN;AQ.prototype.hide.call(this);this.S.Uv();Tz(this);e!==this.rN&&this.player.logVisibility(this.element,!1)};
g.M.pS=function(e){e.target===this.element&&this.ER()};
g.M.ER=function(){var e,K,S,I;var A=((e=this.videoData)==null?0:(K=e.suggestions)==null?0:K.length)?(S=this.videoData)==null?void 0:S.suggestions:[(I=this.videoData)==null?void 0:g.km(I)];if(A.length){g.o3(this.element,"ytp-endscreen-paginate");var k=this.V.Oc(!0,this.V.isFullscreen());if(e=g.mc(this.V))e=e.NC()?48:32,k.width-=e*2;var P=k.width/k.height;I=96/54;K=e=2;var b=Math.max(k.width/96,2),N=Math.max(k.height/54,2);S=A.length;var h=S*4;for(h-=4;h>0&&(e<b||K<N);){var n=e/2,V=K/2,w=e<=b-2&&h>=
V*4,T=K<=N-2&&h>=n*4;if((n+1)/V*I/P>P/(n/(V+1)*I)&&T)h-=n*4,K+=2;else if(w)h-=V*4,e+=2;else if(T)h-=n*4,K+=2;else break}I=!1;h>=12&&S*4-h<=6&&(K>=4||e>=4)&&(I=!0);h=e*96;b=K*54;P=h/b<P?k.height/b:k.width/h;P=Math.min(P,2);h=Math.floor(Math.min(k.width,h*P));b=Math.floor(Math.min(k.height,b*P));k=this.table.element;k.ariaLive="polite";g.Dy(k,h,b);g.Bn(k,{marginLeft:h/-2+"px",marginTop:b/-2+"px"});this.S.QC(g.km(this.videoData));this.S instanceof Sj&&I_(this.S);g.np(this.element,"ytp-endscreen-takeover",
wQ(this));Tz(this);h+=4;b+=4;P=0;k.ariaBusy="true";for(N=0;N<e;N++)for(n=0;n<K;n++)if(V=P,T=0,I&&N>=e-2&&n>=K-2?T=1:n%2===0&&N%2===0&&(n<2&&N<2?n===0&&N===0&&(T=2):T=2),V=g.ti(V+this.Y,S),T!==0){w=this.stills[P];w||(w=new nj(this.player),this.stills[P]=w,k.appendChild(w.element));var Y=Math.floor(b*n/K),u=Math.floor(h*N/e),L=Math.floor(b*(n+T)/K)-Y-4,q=Math.floor(h*(N+T)/e)-u-4;g.rm(w.element,u,Y);g.Dy(w.element,q,L);g.Bn(w.element,"transitionDelay",(n+N)/20+"s");g.np(w.element,"ytp-videowall-still-mini",
T===1);g.np(w.element,"ytp-videowall-still-large",T>2);T=Math.max(q,L);g.np(w.element,"ytp-videowall-still-round-large",T>=256);g.np(w.element,"ytp-videowall-still-round-medium",T>96&&T<256);g.np(w.element,"ytp-videowall-still-round-small",T<=96);V=A[V];w.suggestion!==V&&(w.suggestion=V,T=w.api.J(),Y=g.g1(w.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",ej(w,V,Y),g.Gy(T)&&!w.api.D("web_player_log_click_before_generating_ve_conversion_params")&&(T=V.iB(),Y={},g.YY(w.api,"addEmbedsConversionTrackingParams",
[Y]),T=g.xa(T,Y),w.updateValue("url",T)),(V=(V=V.sessionData)&&V.itct)&&w.api.setTrackingParams(w.element,V));P++}k.ariaBusy="false";g.np(this.element,"ytp-endscreen-paginate",P<S);for(A=this.stills.length-1;A>=P;A--)e=this.stills[A],g.AC(e.element),g.NE(e);this.stills.length=P}};
g.M.onVideoDataChange=function(){var e=this.player.getVideoData(1);this.videoData!==e&&(e!=null&&g.km(e)?(this.Y=0,this.videoData=e,this.ER()):this.player.vY("missg",{vid:(e==null?void 0:e.videoId)||"",cpn:(e==null?void 0:e.clientPlaybackNonce)||""}))};
g.M.U8=function(){this.Y+=this.stills.length;this.ER()};
g.M.Py=function(){this.Y-=this.stills.length;this.ER()};
g.M.Oq=function(){return this.S.iK()};
g.M.Fz=function(e){e===1?(this.Z=!1,this.W=this.videoData.clientPlaybackNonce,this.S.Fe(),this.rN&&this.ER()):(this.Z=!0,this.rN&&wQ(this)&&(e===2?this.S.Cq():e===3&&this.S.Uv()))};
g.M.Bz=function(e){if(e){for(e=0;e<this.stills.length;e++)this.V.logVisibility(this.stills[e].element,!0);this.Fz(1)}else this.W=null,this.Z=!1;this.ER()};
g.M.n3=function(){return this.rN&&wQ(this)};g.X(YF,AQ);YF.prototype.hasSuggestions=function(){var e;return(e=this.S)==null?void 0:e.hasSuggestions()};
YF.prototype.show=function(){if(this.player.getPlayerState()!==3){AQ.prototype.show.call(this);var e=this.L;if(e){var K=this.S.hasSuggestions();g.np(this.element,"ytp-shorts-branded-ui",K);K?e.show():e.hide()}var S;(S=g.mc(this.player))==null||S.R9(!0);this.player.logVisibility(this.element,!0);this.watchButton.i6(!0)}};
YF.prototype.hide=function(){AQ.prototype.hide.call(this);var e;(e=g.mc(this.player))==null||e.R9(!1);this.player.logVisibility(this.element,!1);this.watchButton.i6(!1)};g.X(Iv6,g.NK);g.M=Iv6.prototype;g.M.GC=function(){var e=this.player.getVideoData(),K=e.mutedAutoplay&&(e.limitedPlaybackDurationInSeconds>0||e.endSeconds>0||e.mutedAutoplayDurationMode!==2);if((this.player.isEmbedsShortsMode()||this.L)&&!K)return!0;var S;var I=!!((e==null?0:g.km(e))||(e==null?0:(S=e.suggestions)==null?0:S.length));I=!eZi(this.player)||I;e=e.rK;S=this.player.Cc();return I&&!e&&!S&&!K};
g.M.n3=function(){return this.endScreen.n3()};
g.M.JsA=function(){return this.n3()?this.endScreen.Oq():!1};
g.M.Lr=function(){this.player.TE("endscreen");g.NK.prototype.Lr.call(this)};
g.M.load=function(){var e=this.player.getVideoData();var K=e.transitionEndpointAtEndOfStream;if(K&&K.videoId){var S=this.player.A6().K3.get("heartbeat"),I=g.km(e);!I||K.videoId!==I.videoId||e.jl?(this.player.Ze(K.videoId,void 0,void 0,!0,!0,K),S&&S.zU("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),e=!0):e=!1}else e=!1;e||(g.NK.prototype.load.call(this),this.endScreen.show())};
g.M.unload=function(){g.NK.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.M.onCueRangeEnter=function(e){this.GC()&&(this.endScreen.created||this.endScreen.create(),e.getId()==="load"&&this.load())};
g.M.onCueRangeExit=function(e){e.getId()==="load"&&this.loaded&&this.unload()};
g.M.onVideoDataChange=function(){SNu(this);this.W&&KDK(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.S?this.endScreen=new P1(this.player):this.endScreen=new Vz(this.player),g.c(this,this.endScreen),g.QA(this.player,this.endScreen.element,4))};g.bT("endscreen",Iv6);})(_yt_player);
