(function(g){var window=this;'use strict';var pj=function(e,K){g.C.call(this,{K:"button",kA:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],B:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},X:[{K:"svg",B:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},X:[{K:"g",B:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},X:[{K:"g",B:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
X:[{K:"path",B:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.V=e;this.listen("click",this.onClick,this);this.updateValue("title",g.pX(e,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.vh(K.YN(),this.element))},Stn=function(e){g.C.call(this,
{K:"div",
C:"ytp-miniplayer-ui"});this.Z=!1;this.player=e;this.T(e,"minimized",this.u9);this.T(e,"onStateChange",this.n6t);this.T(e,"documentpictureinpicturechange",this.G0A)},ID6=function(e,K){g.np(e.player.getRootNode(),"ytp-player-minimized",K)},AYu=function(e){g.NK.call(this,e);
this.L=new g.Qv(this);this.S=new Stn(this.player);this.S.hide();g.QA(this.player,this.S.element,4);e.isMinimized()&&(this.load(),g.np(e.getRootNode(),"ytp-player-minimized",!0))};
g.X(pj,g.C);pj.prototype.onClick=function(){this.V.Xt("onExpandMiniplayer")};g.X(Stn,g.C);g.M=Stn.prototype;
g.M.show=function(){this.S=new g.d2(this.gf,null,this);this.S.start();if(!this.Z){this.tooltip=new g.mS(this.player,this);g.c(this,this.tooltip);g.QA(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.F7=new g.Qw(this.player);g.c(this,this.F7);this.progressBar=new g.pM(this.player,this);g.c(this,this.progressBar);g.QA(this.player,this.progressBar.element,4);this.L=new g.C({K:"div",C:"ytp-miniplayer-scrim"});g.c(this,this.L);this.L.As(this.element);this.T(this.L.element,"click",this.OY);
var e=new g.C({K:"button",kA:["ytp-miniplayer-close-button","ytp-button"],B:{"aria-label":"Close"},X:[g.E5()]});g.c(this,e);e.As(this.L.element);this.T(e.element,"click",this.Pc);e=new pj(this.player,this);g.c(this,e);e.As(this.L.element);this.Y=new g.C({K:"div",C:"ytp-miniplayer-controls"});g.c(this,this.Y);this.Y.As(this.L.element);this.T(this.Y.element,"click",this.OY);var K=new g.C({K:"div",C:"ytp-miniplayer-button-container"});g.c(this,K);K.As(this.Y.element);e=new g.C({K:"div",C:"ytp-miniplayer-play-button-container"});
g.c(this,e);e.As(this.Y.element);var S=new g.C({K:"div",C:"ytp-miniplayer-button-container"});g.c(this,S);S.As(this.Y.element);this.j=new g.Ey(this.player,this,!1);g.c(this,this.j);this.j.As(K.element);K=new g.qR(this.player,this);g.c(this,K);K.As(e.element);this.nextButton=new g.Ey(this.player,this,!0);g.c(this,this.nextButton);this.nextButton.As(S.element);this.N=new g.bi(this.player,this,0);g.c(this,this.N);this.N.As(this.L.element);this.W=new g.C({K:"div",C:"ytp-miniplayer-buttons"});g.c(this,
this.W);g.QA(this.player,this.W.element,4);e=new g.C({K:"button",kA:["ytp-miniplayer-close-button","ytp-button"],B:{"aria-label":"Close"},X:[g.E5()]});g.c(this,e);e.As(this.W.element);this.T(e.element,"click",this.Pc);e=new g.C({K:"button",kA:["ytp-miniplayer-replay-button","ytp-button"],B:{"aria-label":"Close"},X:[g.xq()]});g.c(this,e);e.As(this.W.element);this.T(e.element,"click",this.Bsr);e=new pj(this.player,this);g.c(this,e);e.As(this.W.element);this.T(this.player,"presentingplayerstatechange",
this.LS);this.T(this.player,"appresize",this.dN);this.T(this.player,"fullscreentoggled",this.dN);this.dN();this.Z=!0}this.player.getPlayerState()!==0&&g.C.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.M.hide=function(){this.S&&(this.S.dispose(),this.S=void 0);g.C.prototype.hide.call(this);this.player.isMinimized()||(this.Z&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.M.Lr=function(){this.S&&(this.S.dispose(),this.S=void 0);g.C.prototype.Lr.call(this)};
g.M.Pc=function(){this.player.D("kevlar_watch_while_v2")||this.player.stopVideo();this.player.Xt("onCloseMiniplayer")};
g.M.Bsr=function(){this.player.playVideo()};
g.M.OY=function(e){if(e.target===this.L.element||e.target===this.Y.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.M.u9=function(){ID6(this,this.player.isMinimized())};
g.M.G0A=function(){ID6(this,this.player.TL());g.np(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.TL())};
g.M.o7=function(){this.progressBar.sM();this.N.sM()};
g.M.gf=function(){this.o7();this.S&&this.S.start()};
g.M.LS=function(e){g.D(e.state,32)&&this.tooltip.hide()};
g.M.dN=function(){var e=this.player.UV().getPlayerSize().width;g.obl(this.progressBar,0,e,!1);g.xi(this.progressBar)};
g.M.n6t=function(e){this.player.isMinimized()&&(e===0?this.hide():this.show())};
g.M.YN=function(){return this.tooltip};
g.M.QX=function(e,K,S,I,A){var k=0,P=0,b=0,N=g.Ry(e);I=K&&(g.g1(K,"ytp-prev-button")||g.g1(K,"ytp-next-button"));if(K){S=g.g1(K,"ytp-play-button");var h=g.g1(K,"ytp-miniplayer-expand-watch-page-button");I?k=b=12:S?(K=g.sR(K,this.element),b=K.x,k=K.y-12):h&&(b=g.g1(K,"ytp-miniplayer-button-top-left"),k=g.sR(K,this.element),K=g.Ry(K),b?(b=8,k=k.y+40):(b=k.x-N.width+K.width,k=k.y-20))}else b=S-N.width/2,P=25+(A||0);K=this.player.UV().getPlayerSize();A=k+(A||0);N=g.lp(b,0,K.width-N.width-12);A?(e.style.top=
A+"px",e.style.bottom=""):(e.style.top="",e.style.bottom=P+"px");e.style.left=N+"px";P=g.g1(e,"ytp-preview");e.style.visibility=I&&P&&K.height<225?"hidden":""};g.X(AYu,g.NK);g.M=AYu.prototype;g.M.onVideoDataChange=function(){if(this.player.getVideoData()){var e=this.player.getVideoAspectRatio(),K=16/9;e=e>K+.1||e<K-.1;g.np(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",e)}};
g.M.create=function(){g.NK.prototype.create.call(this);this.L.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.M.ME=function(){return!1};
g.M.load=function(){this.player.hideControls();this.S.show()};
g.M.unload=function(){this.player.showControls();this.S.hide()};g.bT("miniplayer",AYu);})(_yt_player);
